"use client";

import { useEffect, useMemo, useState } from "react";
import inventoryService from "../../../services/inventoryService";

const TABS = [["overview", "Overview"], ["stock", "Stock Summary"], ["warehouse", "Warehouse Stock"], ["adjustments", "Adjustments"], ["transfers", "Transfers"], ["low", "Low Stock"], ["valuation", "Valuation"], ["batches", "Batches"], ["ledger", "Ledger"]];
const emptyAdjustment = { productId: "", warehouseId: "", adjustmentType: "adjustment_in", qty: 0, unitCost: 0, batchNo: "", reason: "" };
const emptyTransfer = { productId: "", fromWarehouseId: "", toWarehouseId: "", quantity: 0, unitCost: 0, batchNo: "", note: "", autoPost: true };
function money(value) { return `PKR ${Number(value || 0).toLocaleString()}`; }
function num(value) { return Number(value || 0).toLocaleString(); }
function dateText(value) { return value ? new Date(value).toLocaleDateString() : "-"; }
function ownerLabel(row) { return row.ownerType === "distributor" ? `Distributor ${row.distributorId || row.ownerId || ""}` : "Company"; }
function inputClass() { return "rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-700 outline-none focus:border-cyan-400"; }
function status(value) { const safe = String(value || "active"); const cls = ["posted", "completed", "available", "ok", "active"].includes(safe) ? "bg-emerald-50 text-emerald-700" : ["pending", "draft", "low"].includes(safe) ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-700"; return <span className={`rounded-full px-3 py-1 text-xs font-black ${cls}`}>{safe}</span>; }
function exportCsv(filename, rows = []) { const headers = Object.keys(rows[0] || { empty: "" }); const csv = [headers.join(","), ...rows.map((row) => headers.map((h) => `"${String(row[h] ?? "").replace(/"/g, '""')}"`).join(","))].join("\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url); }
function printPage() { if (typeof window !== "undefined") window.print(); }
function Kpi({ label, value, help }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">{label}</p><p className="mt-3 text-2xl font-black text-slate-950">{value}</p><p className="mt-2 text-sm text-slate-500">{help}</p></div>; }
function Field({ label, children }) { return <label className="grid gap-1 text-xs font-bold uppercase tracking-wide text-slate-500"><span>{label}</span>{children}</label>; }
function Panel({ title, subtitle, children }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-slate-950">{title}</h3>{subtitle ? <p className="mt-1 text-sm text-slate-500">{subtitle}</p> : null}<div className="mt-4">{children}</div></div>; }
function Table({ title, rows = [], columns = [], render }) { return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="font-black text-slate-950">{title}</h3><p className="text-xs text-slate-500">{rows.length} records</p></div><div className="flex gap-2"><button onClick={() => exportCsv(`${title.toLowerCase().replace(/\s+/g, "-")}.csv`, rows)} className="rounded-full border border-slate-200 px-3 py-2 text-xs font-black text-slate-600">Export CSV</button><button onClick={printPage} className="rounded-full border border-slate-200 px-3 py-2 text-xs font-black text-slate-600">Print</button></div></div><div className="overflow-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map((c) => <th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody>{rows.map((row, idx) => <tr key={row._id || row.documentNo || `${title}-${idx}`} className="border-t border-slate-100">{render(row).map((cell, i) => <td key={i} className="px-4 py-3 align-middle text-slate-700">{cell}</td>)}</tr>)}{!rows.length ? <tr><td colSpan={columns.length} className="px-4 py-8 text-center text-slate-400">No records yet.</td></tr> : null}</tbody></table></div></div>; }

export default function InventoryWarehouseFoundationPage({ mode = "inventory" }) {
  const [tab, setTab] = useState(mode === "warehouse" ? "warehouse" : "overview");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [data, setData] = useState({ kpis: {}, summary: [], warehouseSummary: [], adjustments: [], transfers: [], lowStock: [], valuation: [], batches: [], ledgerRows: [], warehouses: [], products: [] });
  const [adjustmentForm, setAdjustmentForm] = useState(emptyAdjustment);
  const [transferForm, setTransferForm] = useState(emptyTransfer);
  const productOptions = useMemo(() => data.products || [], [data.products]);
  const warehouseOptions = useMemo(() => data.warehouses || [], [data.warehouses]);

  async function load() { setLoading(true); setError(""); try { setData(await inventoryService.overview()); } catch (e) { setError(e.message || "Unable to load inventory data"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function action(label, fn) { setSaving(true); setError(""); setNotice(""); try { const res = await fn(); setNotice(res?.message || `${label} completed successfully.`); await load(); return res; } catch (e) { setError(e.message || `${label} failed`); } finally { setSaving(false); } }
  const productById = (id) => productOptions.find((p) => String(p.productId || p._id) === String(id));

  return <div className="space-y-6">
    <div className="rounded-[2rem] bg-gradient-to-r from-slate-950 via-cyan-700 to-emerald-500 p-6 text-white shadow-lg print:bg-white print:text-slate-950"><p className="text-xs font-black uppercase tracking-[0.35em] text-cyan-100 print:text-slate-500">Phase 5 Inventory</p><h2 className="mt-2 text-3xl font-black">Inventory, Warehouse, Transfers & Stock Control</h2><p className="mt-2 max-w-4xl text-sm text-cyan-50 print:text-slate-600">Rawyan ERP inventory now uses stock-ledger based movement control with adjustments, inter-warehouse transfers, low-stock alerts, valuation, batch visibility, warehouse stock cards, export, and print options.</p></div>
    <div className="flex flex-wrap gap-2 print:hidden">{TABS.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`rounded-full px-4 py-2 text-sm font-bold ${tab === key ? "bg-slate-950 text-white" : "bg-white text-slate-600 shadow-sm ring-1 ring-slate-200"}`}>{label}</button>)}</div>
    {error ? <div className="rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-600">{error}</div> : null}{notice ? <div className="rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</div> : null}
    {loading ? <div className="rounded-3xl border border-slate-200 bg-white p-6 text-slate-500 shadow-sm">Loading inventory data…</div> : null}

    {!loading && tab === "overview" ? <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Kpi label="Company Stock" value={num(data.kpis?.totalQty)} help="Available company stock" /><Kpi label="Stock Value" value={money(data.kpis?.totalValue)} help="Ledger-based valuation" /><Kpi label="Low Stock" value={num(data.kpis?.lowStockItems)} help="Products below minimum level" /><Kpi label="Warehouses" value={num(data.kpis?.warehouses)} help="Active warehouse records" /><Kpi label="Products" value={num(data.kpis?.products)} help="Master product records" /><Kpi label="Pending Transfers" value={num(data.kpis?.pendingTransfers)} help="Transfers waiting completion" /><Kpi label="Adjustments" value={num(data.kpis?.adjustments)} help="Stock adjustments posted" /><Kpi label="Batch Lines" value={num(data.kpis?.batchLines)} help="Batch tracked balances" /></div><div className="grid gap-5 xl:grid-cols-2"><Table title="Low Stock Alerts" rows={(data.lowStock || []).slice(0, 10)} columns={["Product", "Available", "Minimum", "Shortage", "Status"]} render={(row) => [row.productName, num(row.balanceQty), num(row.minStockLevel), num(row.shortageQty), status(row.status)]} /><Table title="Recent Ledger" rows={(data.ledgerRows || []).slice(0, 10)} columns={["Date", "Movement", "Product", "Qty", "Warehouse"]} render={(row) => [dateText(row.postedAt || row.createdAt), row.movementType, row.productName, `${row.direction === "out" ? "-" : "+"}${num(row.qty)}`, row.warehouseName || "-"]} /></div></div> : null}

    {!loading && tab === "stock" ? <Table title="Product Stock Summary" rows={data.summary || []} columns={["Owner", "Product", "In", "Out", "Available", "Value"]} render={(row) => [ownerLabel(row), row.productName || "-", num(row.inQty), num(row.outQty), num(row.balanceQty), money(row.stockValue)]} /> : null}
    {!loading && tab === "warehouse" ? <div className="space-y-5"><Table title="Warehouses" rows={warehouseOptions} columns={["Warehouse", "City", "Manager", "Capacity", "Status"]} render={(row) => [row.name || row.warehouseName || row.warehouseId, row.city || "-", row.managerName || "-", num(row.capacity), status(row.status || "active")]} /><Table title="Warehouse Stock Detail" rows={data.warehouseSummary || []} columns={["Owner", "Warehouse", "Product", "Batch", "Available", "Value"]} render={(row) => [ownerLabel(row), row.warehouseName || row.warehouseId || "Main Warehouse", row.productName || "-", row.batchNo || "-", num(row.balanceQty), money(row.stockValue)]} /></div> : null}

    {!loading && tab === "adjustments" ? <div className="space-y-5"><Panel title="Post Stock Adjustment" subtitle="Use only for opening stock, count corrections, damaged stock, or expiry stock."><div className="grid gap-3 lg:grid-cols-4"><Field label="Product"><select value={adjustmentForm.productId} onChange={(e) => { const p = productById(e.target.value); setAdjustmentForm((prev) => ({ ...prev, productId: e.target.value, unitCost: p?.costPrice || prev.unitCost })); }} className={inputClass()}><option value="">Select product</option>{productOptions.map((p) => <option key={p._id} value={p.productId || p._id}>{p.name}</option>)}</select></Field><Field label="Warehouse"><select value={adjustmentForm.warehouseId} onChange={(e) => setAdjustmentForm((p) => ({ ...p, warehouseId: e.target.value }))} className={inputClass()}><option value="">Select warehouse</option>{warehouseOptions.map((w) => <option key={w._id} value={w.warehouseId || w._id}>{w.name}</option>)}</select></Field><Field label="Type"><select value={adjustmentForm.adjustmentType} onChange={(e) => setAdjustmentForm((p) => ({ ...p, adjustmentType: e.target.value }))} className={inputClass()}><option value="adjustment_in">Adjustment In</option><option value="adjustment_out">Adjustment Out</option><option value="damage_out">Damage Out</option><option value="expiry_out">Expiry Out</option></select></Field><Field label="Qty"><input value={adjustmentForm.qty} onChange={(e) => setAdjustmentForm((p) => ({ ...p, qty: e.target.value }))} type="number" className={inputClass()} /></Field><Field label="Unit Cost"><input value={adjustmentForm.unitCost} onChange={(e) => setAdjustmentForm((p) => ({ ...p, unitCost: e.target.value }))} type="number" className={inputClass()} /></Field><Field label="Batch No"><input value={adjustmentForm.batchNo} onChange={(e) => setAdjustmentForm((p) => ({ ...p, batchNo: e.target.value }))} className={inputClass()} /></Field><Field label="Reason"><input value={adjustmentForm.reason} onChange={(e) => setAdjustmentForm((p) => ({ ...p, reason: e.target.value }))} className={inputClass()} /></Field><button disabled={saving} onClick={() => action("Stock adjustment", () => inventoryService.createAdjustment(adjustmentForm)).then(() => setAdjustmentForm(emptyAdjustment))} className="rounded-2xl bg-slate-950 px-4 py-3 text-sm font-black text-white lg:self-end">Post Adjustment</button></div></Panel><Table title="Stock Adjustments" rows={data.adjustments || []} columns={["Document", "Product", "Warehouse", "Type", "Qty", "Value", "Status"]} render={(row) => [row.documentNo, row.productName, row.warehouseName || "-", row.adjustmentType, num(row.qty), money(row.totalValue), status(row.status)]} /></div> : null}

    {!loading && tab === "transfers" ? <div className="space-y-5"><Panel title="Create Warehouse Transfer" subtitle="Transfers post one stock-out and one stock-in ledger line."><div className="grid gap-3 lg:grid-cols-4"><Field label="Product"><select value={transferForm.productId} onChange={(e) => { const p = productById(e.target.value); setTransferForm((prev) => ({ ...prev, productId: e.target.value, unitCost: p?.costPrice || prev.unitCost })); }} className={inputClass()}><option value="">Select product</option>{productOptions.map((p) => <option key={p._id} value={p.productId || p._id}>{p.name}</option>)}</select></Field><Field label="From Warehouse"><select value={transferForm.fromWarehouseId} onChange={(e) => setTransferForm((p) => ({ ...p, fromWarehouseId: e.target.value }))} className={inputClass()}><option value="">From warehouse</option>{warehouseOptions.map((w) => <option key={w._id} value={w.warehouseId || w._id}>{w.name}</option>)}</select></Field><Field label="To Warehouse"><select value={transferForm.toWarehouseId} onChange={(e) => setTransferForm((p) => ({ ...p, toWarehouseId: e.target.value }))} className={inputClass()}><option value="">To warehouse</option>{warehouseOptions.map((w) => <option key={w._id} value={w.warehouseId || w._id}>{w.name}</option>)}</select></Field><Field label="Qty"><input value={transferForm.quantity} onChange={(e) => setTransferForm((p) => ({ ...p, quantity: e.target.value }))} type="number" className={inputClass()} /></Field><Field label="Unit Cost"><input value={transferForm.unitCost} onChange={(e) => setTransferForm((p) => ({ ...p, unitCost: e.target.value }))} type="number" className={inputClass()} /></Field><Field label="Batch No"><input value={transferForm.batchNo} onChange={(e) => setTransferForm((p) => ({ ...p, batchNo: e.target.value }))} className={inputClass()} /></Field><Field label="Note"><input value={transferForm.note} onChange={(e) => setTransferForm((p) => ({ ...p, note: e.target.value }))} className={inputClass()} /></Field><button disabled={saving} onClick={() => action("Stock transfer", () => inventoryService.createTransfer(transferForm)).then(() => setTransferForm(emptyTransfer))} className="rounded-2xl bg-slate-950 px-4 py-3 text-sm font-black text-white lg:self-end">Post Transfer</button></div></Panel><Table title="Warehouse Transfers" rows={data.transfers || []} columns={["Product", "From", "To", "Qty", "Status", "Action"]} render={(row) => [row.productName, row.fromWarehouseName, row.toWarehouseName, num(row.quantity), status(row.status), row.status !== "completed" ? <button key="c" onClick={() => action("Complete transfer", () => inventoryService.completeTransfer(row._id))} className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">Complete</button> : "-"]} /></div> : null}

    {!loading && tab === "low" ? <Table title="Low Stock Report" rows={data.lowStock || []} columns={["Product", "Available", "Minimum", "Shortage", "Status"]} render={(row) => [row.productName, num(row.balanceQty), num(row.minStockLevel), num(row.shortageQty), status(row.status)]} /> : null}
    {!loading && tab === "valuation" ? <Table title="Stock Valuation" rows={data.valuation || []} columns={["Owner", "Product", "Available", "Average Cost", "Value"]} render={(row) => [ownerLabel(row), row.productName, num(row.balanceQty), money(row.averageCost), money(row.stockValue)]} /> : null}
    {!loading && tab === "batches" ? <Table title="Batch / Lot Stock" rows={data.batches || []} columns={["Warehouse", "Product", "Batch", "Available", "Value", "Status"]} render={(row) => [row.warehouseName || "-", row.productName, row.batchNo || "-", num(row.balanceQty), money(row.stockValue), status(row.status)]} /> : null}
    {!loading && tab === "ledger" ? <Table title="Inventory Ledger" rows={data.ledgerRows || []} columns={["Date", "Owner", "Warehouse", "Movement", "Product", "Batch", "Qty", "Reference"]} render={(row) => [dateText(row.postedAt || row.createdAt), ownerLabel(row), row.warehouseName || "-", row.movementType, row.productName, row.batchNo || "-", `${row.direction === "out" ? "-" : "+"}${num(row.qty)}`, row.referenceNo || "-"]} /> : null}
  </div>;
}
