export const PRODUCT_CATEGORIES = [
  { label: 'Wipes', value: 'Wipes', subCategories: ['Royal Baby Wipes', 'Mamia Wipes 42-sheets', 'Mamia Crown Wipes', 'Mamia Wipes Gentle', 'Wipes Premium'] },
  { label: 'Xtra Eco', value: 'Xtra Eco', subCategories: ['Xtra Eco'] },
  { label: 'ADULT', value: 'ADULT', subCategories: ['Adult'] },
  { label: 'Optima', value: 'Optima', subCategories: ['Optima Soap', 'Optima Wipes'] },
  { label: 'Mamia Crown Eco', value: 'Mamia Crown Eco', subCategories: ['Mamia Crown Eco'] },
  { label: 'Mamia Crown Jumbo', value: 'Mamia Crown Jumbo', subCategories: ['Mamia Crown Jumbo'] },
  { label: 'Mamia Dishwash', value: 'Mamia Dishwash', subCategories: ['Mamia Dishwash Lemon', 'Mamia Dishwash'] },
  { label: 'Mamia Soap', value: 'Mamia Soap', subCategories: ['Mamia Soap'] },
  { label: 'Mamia Pads', value: 'Mamia Pads', subCategories: ['Value Pack', 'Single Pack', 'Travel Pack'] },
  { label: 'Razor', value: 'Razor', subCategories: ['Razor'] },
  { label: 'Xtra', value: 'Xtra', subCategories: ['Xtra Jumbo'] },
  { label: 'BABY DIAPER', value: 'BABY DIAPER', subCategories: ['Jumbo Pack', 'Twin Pack', 'Small Pack'] },
  { label: 'Royal Baby', value: 'Royal Baby', subCategories: ['Royal Baby Jumbo', 'Royal Baby Eco'] },
  { label: 'Royal Baby Wipes', value: 'Royal Baby Wipes', subCategories: ['Royal Baby Wipes'] },
  { label: 'Comfery Adult', value: 'Comfery Adult', subCategories: ['Comfery Adult'] },
];

export const PRODUCT_TEMPLATE_HEADERS = [
  'Code', 'Bar Code', 'BulkBarCode', 'Product Name', 'Size', 'Alternative Name', 'Carton Size', 'Pack Size',
  'Retail Price', 'Wholesale Price', 'Trade Price', 'Taxable Price', 'Cost Price', 'Discount Per', 'Unit Scheme',
  'is Tax From Customer', 'Is Tax Applied On Bonus', 'Is Tax Applied After Discount And Scheme',
  'Is Discount Applied After Scheme', 'Weight', 'Weight Unit Name', 'Sub Category Name', 'Tax Per', 'FED Per',
  'Company Name', 'Category Name', 'Tax Type Name', 'Activation Type',
];

export const PRODUCT_COLUMN_MAP = {
  code: 'code',
  barcode: 'barcode',
  bulkbarcode: 'bulkBarcode',
  productname: 'name',
  size: 'size',
  alternativename: 'alternativeName',
  cartonsize: 'cartonSize',
  packsize: 'packSize',
  retailprice: 'retailPrice',
  wholesaleprice: 'wholesalePrice',
  tradeprice: 'tradePrice',
  taxableprice: 'taxablePrice',
  costprice: 'costPrice',
  discountper: 'discountPer',
  unitscheme: 'unitScheme',
  istaxfromcustomer: 'isTaxFromCustomer',
  istaxappliedonbonus: 'isTaxAppliedOnBonus',
  istaxappliedafterdiscountandscheme: 'isTaxAppliedAfterDiscountAndScheme',
  isdiscountappliedafterscheme: 'isDiscountAppliedAfterScheme',
  weight: 'weight',
  weightunitname: 'weightUnitName',
  subcategoryname: 'subCategory',
  taxper: 'taxPer',
  fedper: 'fedPer',
  companyname: 'companyName',
  categoryname: 'category',
  taxtypename: 'taxTypeName',
  activationtype: 'activationType',
};

export const PRODUCT_EMPTY_FORM = {
  code: '',
  productId: '',
  name: '',
  alternativeName: '',
  companyId: '',
  companyName: '',
  category: '',
  subCategory: '',
  size: '',
  unit: '',
  weight: '',
  weightUnitName: '',
  cartonSize: '',
  packSize: '',
  retailPrice: '',
  wholesalePrice: '',
  tradePrice: '',
  taxablePrice: '',
  customerPrice: '',
  costPrice: '',
  discountPer: '',
  unitScheme: '',
  isTaxFromCustomer: false,
  isTaxAppliedOnBonus: false,
  isTaxAppliedAfterDiscountAndScheme: false,
  isDiscountAppliedAfterScheme: false,
  taxPer: '',
  fedPer: '',
  taxTypeName: '',
  activationType: 'Active',
  barcode: '',
  bulkBarcode: '',
  sku: '',
  description: '',
};