const mongoose = require("mongoose");
const EmbeddedPermissionSchema = new mongoose.Schema({ actions: { type: [String], default: [] }, scope: { type: String, default: "company" } }, { _id: false });
const UserSchema = new mongoose.Schema({
  username: { type: String, unique: true, lowercase: true, trim: true }, fullName: { type: String, required: true }, mobile: { type: String, trim: true, unique: true, sparse: true }, role: { type: String, required: true },
  roleId: { type: mongoose.Schema.Types.ObjectId, ref: "Role" }, roleKey: { type: String, trim: true, lowercase: true }, portalType: { type: String, trim: true }, landingPath: { type: String, trim: true, default: "/portals" }, permissions: { type: Map, of: EmbeddedPermissionSchema, default: undefined }, enabledModules: { type: [String], default: undefined }, mobileAccess: { type: Boolean, default: false }, mobileModules: { type: [String], default: undefined },
  status: { type: String, enum: ["active", "deactive", "inactive"], default: "active" }, passwordHash: { type: String, required: true }, email: { type: String, trim: true, lowercase: true },
  language: { type: String, enum: ["en", "ur", "ar"], default: "en" }, theme: { type: String, enum: ["light", "dark", "system"], default: "light" },
  companyId: { type: String, trim: true }, companyName: { type: String, trim: true }, erpTemplateKey: { type: String, trim: true, default: "distribution_erp" }, companyBranchId: { type: String, trim: true }, branchId: { type: String, trim: true }, branchNameOrNumber: { type: String, trim: true }, warehouseId: { type: String, trim: true }, warehouseName: { type: String, trim: true },
  regionId: { type: String, trim: true }, regionName: { type: String, trim: true }, zoneId: { type: String, trim: true }, zoneName: { type: String, trim: true }, areaId: { type: String, trim: true }, areaName: { type: String, trim: true }, shopId: { type: String, trim: true }, shopName: { type: String, trim: true }, address: { type: String, trim: true }, shopAddress: { type: String, trim: true },
  cnicNo: { type: String, trim: true }, mobileNumber: { type: String, trim: true }, phoneNumber: { type: String, trim: true }, gpsLatitude: { type: String, trim: true }, gpsLongitude: { type: String, trim: true },
  managerId: { type: String, trim: true }, managerName: { type: String, trim: true }, warehouseManagerId: { type: String, trim: true }, warehouseManagerName: { type: String, trim: true }, accountantId: { type: String, trim: true }, accountantName: { type: String, trim: true }, distributorId: { type: String, trim: true }, distributorName: { type: String, trim: true }, driverId: { type: String, trim: true }, driverName: { type: String, trim: true }, deliveryBoyId: { type: String, trim: true }, deliveryBoyName: { type: String, trim: true }, salesmanId: { type: String, trim: true }, salesmanName: { type: String, trim: true }, orderBookerId: { type: String, trim: true }, orderBookerName: { type: String, trim: true }, customerId: { type: String, trim: true }, customerName: { type: String, trim: true }, supplierId: { type: String, trim: true }, supplierName: { type: String, trim: true },
  supplierWarehouseId1: { type: String, trim: true }, supplierWarehouseName1: { type: String, trim: true }, supplierWarehouseId2: { type: String, trim: true }, supplierWarehouseName2: { type: String, trim: true }, userId: { type: String, trim: true }, territoryId: { type: String, trim: true }, territoryName: { type: String, trim: true }, fieldId: { type: String, trim: true }, fieldName: { type: String, trim: true }, businessType: { type: String, trim: true }, businessName: { type: String, trim: true }, documentPdf: { type: String, trim: true }, documentPdfName: { type: String, trim: true }, documentPdfUrl: { type: String, trim: true }, documentPdfObjectKey: { type: String, trim: true },
}, { timestamps: true });
UserSchema.index({ userId: 1 }, { unique: true, partialFilterExpression: { userId: { $exists: true, $type: "string", $ne: "" } } });
UserSchema.index({ companyId: 1, roleId: 1 }); UserSchema.index({ companyId: 1, portalType: 1 });
module.exports = mongoose.models.User || mongoose.model("User", UserSchema);
