const express = require("express");
const Company = require("../../models/Company");
const Plan = require("../../models/Plan");
const Subscription = require("../../models/Subscription");
const { getCurrentCompanySubscription, getLifecycleStatusFromSubscriptionStatus } = require("../../services/subscriptionLifecycleService");
const { buildAuditContext, fireAndForgetAudit, ensureCompanyOrThrow, ensurePlatformSeedData } = require("./common");
const { logCompanyLifecycleChange, logSubscriptionAssigned } = require("../../services/platformAuditLogService");

const router = express.Router();
router.post('/plans', async (req,res)=>{ try{ const plan=await Plan.create(req.body||{}); return res.status(201).json({ success:true, plan }); } catch(error){ if(error?.code===11000) return res.status(409).json({ success:false, message:'Plan code already exists' }); return res.status(500).json({ success:false, message:error.message||'Failed to create plan' }); } });
router.get('/plans', async (_req,res)=>{ await ensurePlatformSeedData(); return res.json({ success:true, plans: await Plan.find().sort({ isDefault:-1, name:1 }).lean() }); });
router.get('/plans/:planId', async (req,res)=>{ const plan=await Plan.findById(req.params.planId).lean(); if(!plan) return res.status(404).json({ success:false, message:'Plan not found' }); return res.json({ success:true, plan }); });
router.put('/plans/:planId', async (req,res)=>{ const plan=await Plan.findByIdAndUpdate(req.params.planId, req.body||{}, { new:true, runValidators:true }); if(!plan) return res.status(404).json({ success:false, message:'Plan not found' }); return res.json({ success:true, plan }); });
router.post('/companies/:companyId/subscription', async (req,res)=>{ try{ const company=await Company.findById(req.params.companyId); if(!company) return res.status(404).json({ success:false, message:'Company not found' }); const plan=await Plan.findById(req.body?.planId).lean(); if(!plan) return res.status(404).json({ success:false, message:'Plan not found' }); const subscription=await Subscription.create({ companyId:company._id, planId:plan._id, billingCycle:req.body?.billingCycle||plan.billingType||'monthly', startDate:req.body?.startDate||new Date(), endDate:req.body?.endDate, status:req.body?.status||'active', paymentStatus:req.body?.paymentStatus||'pending', notes:req.body?.notes||'', createdBy:req.user?.uid||req.user?._id }); company.subscriptionId=subscription._id; company.lifecycleStatus=getLifecycleStatusFromSubscriptionStatus(subscription.status); await company.save(); fireAndForgetAudit(logSubscriptionAssigned(buildAuditContext(req), company, subscription)); return res.status(201).json({ success:true, company, subscription }); } catch(error){ return res.status(error.status||500).json({ success:false, message:error.message||'Failed to assign subscription' }); } });
router.get('/companies/:companyId/subscription', async (req,res)=>{ try{ await ensureCompanyOrThrow(req.params.companyId); const subscription=await getCurrentCompanySubscription(req.params.companyId); return res.json({ success:true, subscription }); } catch(error){ return res.status(error.status||500).json({ success:false, message:error.message||'Failed to load subscription' }); } });
async function updateCompanyLifecycle(req,res,status){ try{ const company=await Company.findById(req.params.companyId); if(!company) return res.status(404).json({ success:false, message:'Company not found' }); const before={ lifecycleStatus: company.lifecycleStatus }; company.lifecycleStatus=status; if(status==='active') company.activatedAt=new Date(); if(status==='suspended') company.suspendedAt=new Date(); if(status==='expired') company.expiredAt=new Date(); await company.save(); if(company.subscriptionId){ await Subscription.findByIdAndUpdate(company.subscriptionId,{ status }); } fireAndForgetAudit(logCompanyLifecycleChange(buildAuditContext(req), company, before.lifecycleStatus, status)); return res.json({ success:true, company }); } catch(error){ return res.status(error.status||500).json({ success:false, message:error.message||'Failed lifecycle update' }); } }
router.post('/companies/:companyId/activate',(req,res)=>updateCompanyLifecycle(req,res,'active'));
router.post('/companies/:companyId/suspend',(req,res)=>updateCompanyLifecycle(req,res,'suspended'));
router.post('/companies/:companyId/mark-expired',(req,res)=>updateCompanyLifecycle(req,res,'expired'));
router.post('/companies/:companyId/reactivate',(req,res)=>updateCompanyLifecycle(req,res,'active'));
module.exports = router;
