const express = require("express");
const { requireAuth } = require("../../../../utils/auth");
const { requireCompanyModule } = require("../../../../core/access/companyAccessGuard");
const c = require("./trading.controller");
const router = express.Router();
router.use(requireAuth, requireCompanyModule("trading"));
router.get("/overview", c.overview);
router.get("/shipments", c.listShipments); router.post("/shipments", c.createShipment); router.patch("/shipments/:id/status", c.updateShipmentStatus);
router.get("/letters-of-credit", c.listLettersOfCredit); router.post("/letters-of-credit", c.createLetterOfCredit);
router.get("/landed-costs", c.listLandedCosts); router.post("/landed-costs", c.createLandedCost);
router.get("/products", c.listProducts); router.get("/warehouses", c.listWarehouses);
router.get("/print/:type/:id", c.printDocument);
module.exports = router;
