const TradingShipment = require("../../../../models/TradingShipment");
const LetterOfCredit = require("../../../../models/LetterOfCredit");
const LandedCost = require("../../../../models/LandedCost");
const Product = require("../../../../models/Product");
const Warehouse = require("../../../../models/Warehouse");
const InventoryLedger = require("../../../../models/InventoryLedger");
const { asText, getScopedModels, scopedCompanyId } = require("../../../../services/scopedModels");
function companyIdFrom(req){return scopedCompanyId(req)}
function uidFrom(req){return asText(req.user?.uid||req.user?._id||req.user?.userId)}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
function money(v){return Math.round(n(v)*100)/100}
function docNo(prefix){return `${prefix}-${new Date().toISOString().slice(0,10).replace(/-/g,"")}-${Date.now().toString().slice(-6)}`}
function statusEntry(status,userId,note=""){return{status,changedBy:userId,changedAt:new Date(),note}}
async function scoped(req){return getScopedModels(req,{TradingShipmentModel:TradingShipment,LetterOfCreditModel:LetterOfCredit,LandedCostModel:LandedCost,ProductModel:Product,WarehouseModel:Warehouse,InventoryLedgerModel:InventoryLedger})}
function line(raw={},i=0){const qty=n(raw.qty||raw.quantity||1);const unitCost=money(raw.unitCost||raw.price||0);const unitPrice=money(raw.unitPrice||raw.salePrice||unitCost);const taxPercent=n(raw.taxPercent);const discountValue=money(raw.discountValue||0);const taxValue=money(Math.max(0,qty*unitPrice-discountValue)*taxPercent/100);return{lineNo:i+1,productId:asText(raw.productId),productCode:asText(raw.productCode||raw.sku),productName:asText(raw.productName||"Trade item"),uom:asText(raw.uom||"unit"),qty,unitCost,unitPrice,discountValue,taxPercent,taxValue,netLineAmount:money(qty*unitPrice-discountValue+taxValue),batchNo:asText(raw.batchNo),notes:asText(raw.notes)}}
function totals(lines=[]){const subtotal=money(lines.reduce((s,l)=>s+n(l.qty)*n(l.unitPrice),0));const discountTotal=money(lines.reduce((s,l)=>s+n(l.discountValue),0));const taxTotal=money(lines.reduce((s,l)=>s+n(l.taxValue),0));return{subtotal,discountTotal,taxTotal,grandTotal:money(subtotal-discountTotal+taxTotal)}}
async function overview(req){const{TradingShipmentModel,LetterOfCreditModel,LandedCostModel}=await scoped(req);const companyId=companyIdFrom(req);const [shipments,activeLc,landed]=await Promise.all([TradingShipmentModel.countDocuments({companyId,status:{$nin:["closed","cancelled"]}}),LetterOfCreditModel.countDocuments({companyId,status:{$in:["opened","amended"]}}),LandedCostModel.aggregate([{$match:{companyId,status:"posted"}},{$group:{_id:null,total:{$sum:"$totalCost"}}}]).catch(()=>[])]);const recent=await TradingShipmentModel.find({companyId}).sort({createdAt:-1}).limit(8).lean();return{ok:true,kpis:{openShipments:shipments,activeLc,landedCost:landed[0]?.total||0},recentShipments:recent}}
async function listShipments(req){const{TradingShipmentModel}=await scoped(req);const filter={companyId:companyIdFrom(req)};if(req.query.shipmentType)filter.shipmentType=asText(req.query.shipmentType);if(req.query.status)filter.status=asText(req.query.status);return{ok:true,shipments:await TradingShipmentModel.find(filter).sort({createdAt:-1}).limit(400).lean()}}
async function createShipment(req){const{TradingShipmentModel}=await scoped(req);const b=req.body||{},companyId=companyIdFrom(req);if(!companyId)throw new Error("Company is required");const lines=(Array.isArray(b.lines)?b.lines:[]).map(line);const t=totals(lines);const shipment=await TradingShipmentModel.create({companyId,shipmentNo:asText(b.shipmentNo)||docNo(asText(b.shipmentType)==="export"?"EXP":"IMP"),shipmentType:asText(b.shipmentType||"import"),supplierId:asText(b.supplierId),supplierName:asText(b.supplierName),customerId:asText(b.customerId),customerName:asText(b.customerName),lcId:asText(b.lcId),lcNo:asText(b.lcNo),containerNo:asText(b.containerNo),blNo:asText(b.blNo),vesselName:asText(b.vesselName),originPort:asText(b.originPort),destinationPort:asText(b.destinationPort),eta:b.eta?new Date(b.eta):undefined,etd:b.etd?new Date(b.etd):undefined,currency:asText(b.currency||"USD"),exchangeRate:n(b.exchangeRate||1),warehouseId:asText(b.warehouseId),warehouseName:asText(b.warehouseName),lines,totals:t,status:asText(b.status||"booked"),documentUrl:asText(b.documentUrl),statusHistory:[statusEntry(asText(b.status||"booked"),uidFrom(req),"Shipment created")],notes:asText(b.notes)});return{ok:true,shipment}}
async function updateShipmentStatus(req){const{TradingShipmentModel,InventoryLedgerModel}=await scoped(req);const companyId=companyIdFrom(req);const shipment=await TradingShipmentModel.findOne({_id:req.params.id,companyId});if(!shipment)throw new Error("Shipment not found");const next=asText(req.body?.status||shipment.status);shipment.status=next;shipment.statusHistory.push(statusEntry(next,uidFrom(req),asText(req.body?.notes)));if(next==="received"&&shipment.shipmentType==="import"&&!shipment.receivedAt){shipment.receivedAt=new Date();for(const l of shipment.lines||[])if(l.productId)await InventoryLedgerModel.create({companyId,ownerType:"company",ownerId:companyId,warehouseId:shipment.warehouseId,warehouseName:shipment.warehouseName,productId:l.productId,productCode:l.productCode,productName:l.productName,batchNo:l.batchNo,movementType:"import_receipt",direction:"in",qty:n(l.qty),unitCost:money(l.unitCost+shipment.landedCostPerUnit),totalValue:money(n(l.qty)*(n(l.unitCost)+n(shipment.landedCostPerUnit))),referenceType:"trading_shipment",referenceId:shipment._id,referenceNo:shipment.shipmentNo,postedAt:new Date(),postedByUserId:uidFrom(req)})}await shipment.save();return{ok:true,shipment}}
async function listLettersOfCredit(req){const{LetterOfCreditModel}=await scoped(req);return{ok:true,lettersOfCredit:await LetterOfCreditModel.find({companyId:companyIdFrom(req)}).sort({createdAt:-1}).limit(300).lean()}}
async function createLetterOfCredit(req){const{LetterOfCreditModel}=await scoped(req);const b=req.body||{},companyId=companyIdFrom(req);const lc=await LetterOfCreditModel.create({companyId,lcNo:asText(b.lcNo)||docNo("LC"),bankName:asText(b.bankName),supplierId:asText(b.supplierId),supplierName:asText(b.supplierName),currency:asText(b.currency||"USD"),amount:money(b.amount),exchangeRate:n(b.exchangeRate||1),issueDate:b.issueDate?new Date(b.issueDate):undefined,expiryDate:b.expiryDate?new Date(b.expiryDate):undefined,status:asText(b.status||"opened"),documentUrl:asText(b.documentUrl),notes:asText(b.notes)});return{ok:true,letterOfCredit:lc}}
async function listLandedCosts(req){const{LandedCostModel}=await scoped(req);return{ok:true,landedCosts:await LandedCostModel.find({companyId:companyIdFrom(req)}).sort({createdAt:-1}).limit(300).lean()}}
async function createLandedCost(req){const{LandedCostModel,TradingShipmentModel}=await scoped(req);const b=req.body||{},companyId=companyIdFrom(req);const total=money(n(b.freight)+n(b.customsDuty)+n(b.clearing)+n(b.insurance)+n(b.otherCharges));let shipment=null;if(b.shipmentId)shipment=await TradingShipmentModel.findOne({_id:b.shipmentId,companyId});const landed=await LandedCostModel.create({companyId,costNo:asText(b.costNo)||docNo("LCOST"),shipmentId:shipment?._id,shipmentNo:asText(shipment?.shipmentNo||b.shipmentNo),freight:money(b.freight),customsDuty:money(b.customsDuty),clearing:money(b.clearing),insurance:money(b.insurance),otherCharges:money(b.otherCharges),totalCost:total,allocationMethod:asText(b.allocationMethod||"value"),status:asText(b.status||"posted"),notes:asText(b.notes)});if(shipment){const qty=(shipment.lines||[]).reduce((s,l)=>s+n(l.qty),0)||1;shipment.landedCostTotal=money(n(shipment.landedCostTotal)+total);shipment.landedCostPerUnit=money(n(shipment.landedCostTotal)/qty);await shipment.save()}return{ok:true,landedCost:landed,shipment}}
async function listProducts(req){const{ProductModel}=await scoped(req);return{ok:true,products:await ProductModel.find({companyId:companyIdFrom(req)}).sort({name:1}).limit(500).lean().catch(()=>[])}}
async function listWarehouses(req){const{WarehouseModel}=await scoped(req);return{ok:true,warehouses:await WarehouseModel.find({companyId:companyIdFrom(req)}).sort({name:1}).limit(200).lean().catch(()=>[])}}
async function printDocument(req){const{TradingShipmentModel,LetterOfCreditModel,LandedCostModel}=await scoped(req);const companyId=companyIdFrom(req),type=asText(req.params.type),id=req.params.id;let doc=null;if(type==="shipment")doc=await TradingShipmentModel.findOne({_id:id,companyId}).lean();if(type==="lc")doc=await LetterOfCreditModel.findOne({_id:id,companyId}).lean();if(type==="landed-cost")doc=await LandedCostModel.findOne({_id:id,companyId}).lean();if(!doc)throw new Error("Document not found");return{ok:true,type,document:doc,printedAt:new Date()}}
module.exports={overview,listShipments,createShipment,updateShipmentStatus,listLettersOfCredit,createLetterOfCredit,listLandedCosts,createLandedCost,listProducts,listWarehouses,printDocument};
