const CustomerAsset = require("../../models/CustomerAsset");
const AmcContract = require("../../models/AmcContract");
const ServiceTicket = require("../../models/ServiceTicket");
const ServiceOrder = require("../../models/ServiceOrder");
const Product = require("../../models/Product");
const User = require("../../models/User");
const InventoryLedger = require("../../models/InventoryLedger");
const { asText, getScopedModels, scopedCompanyId } = require("../../services/scopedModels");
function companyIdFrom(req) { return scopedCompanyId(req); }
function uidFrom(req) { return asText(req.user?.uid || req.user?._id || req.user?.userId); }
function n(v) { const x = Number(v); return Number.isFinite(x) ? x : 0; }
function money(v) { return Math.round(n(v) * 100) / 100; }
function docNo(prefix) { return `${prefix}-${new Date().toISOString().slice(0,10).replace(/-/g,"")}-${Date.now().toString().slice(-6)}`; }
function statusEntry(status, userId, note="") { return { status, changedBy: userId, changedAt: new Date(), note }; }
async function scoped(req) { return getScopedModels(req, { CustomerAssetModel: CustomerAsset, AmcContractModel: AmcContract, ServiceTicketModel: ServiceTicket, ServiceOrderModel: ServiceOrder, ProductModel: Product, UserModel: User, InventoryLedgerModel: InventoryLedger }); }
function lineTotals(lines=[]) { const subtotal = lines.reduce((s,l)=>s+n(l.qty)*n(l.unitPrice),0); const discountTotal = lines.reduce((s,l)=>s+n(l.discountValue),0); const taxTotal = lines.reduce((s,l)=>s+n(l.taxValue),0); return { subtotal: money(subtotal), discountTotal: money(discountTotal), taxTotal: money(taxTotal), grandTotal: money(subtotal-discountTotal+taxTotal) }; }
function normalizeLine(raw={}, i=0) { const qty=n(raw.qty||raw.quantity||1); const unitPrice=money(raw.unitPrice||raw.price||0); const taxPercent=n(raw.taxPercent); const discountValue=money(raw.discountValue||raw.discount||0); const taxable=Math.max(0, qty*unitPrice-discountValue); const taxValue=money(taxable*taxPercent/100); return { lineNo:i+1, productId:asText(raw.productId), productCode:asText(raw.productCode||raw.sku), productName:asText(raw.productName||"Spare part/service"), uom:asText(raw.uom||"unit"), qty, unitCost:money(raw.unitCost), unitPrice, discountValue, taxPercent, taxValue, netLineAmount:money(taxable+taxValue), batchNo:asText(raw.batchNo), notes:asText(raw.notes) }; }
async function overview(req) { const { CustomerAssetModel, AmcContractModel, ServiceTicketModel, ServiceOrderModel } = await scoped(req); const companyId=companyIdFrom(req); const [assets, contracts, openTickets, orders] = await Promise.all([CustomerAssetModel.countDocuments({companyId}), AmcContractModel.countDocuments({companyId,status:"active"}), ServiceTicketModel.countDocuments({companyId,status:{$in:["open","assigned","in_progress"]}}), ServiceOrderModel.find({companyId}).sort({createdAt:-1}).limit(8).lean()]); const revenue = await ServiceOrderModel.aggregate([{ $match:{companyId,status:{$in:["completed","invoiced"]}}},{ $group:{_id:null,total:{$sum:"$totals.grandTotal"}}}]).catch(()=>[]); return { ok:true, kpis:{ assets, activeContracts:contracts, openTickets, serviceRevenue: revenue[0]?.total || 0 }, recentOrders:orders }; }
async function listAssets(req){ const { CustomerAssetModel }=await scoped(req); const filter={companyId:companyIdFrom(req)}; if(req.query.status) filter.status=asText(req.query.status); return { ok:true, assets: await CustomerAssetModel.find(filter).sort({createdAt:-1}).limit(300).lean() }; }
async function createAsset(req){ const { CustomerAssetModel }=await scoped(req); const b=req.body||{}, companyId=companyIdFrom(req); if(!companyId) throw new Error("Company is required"); const asset=await CustomerAssetModel.create({companyId, assetNo:asText(b.assetNo)||docNo("ASSET"), customerId:asText(b.customerId), customerName:asText(b.customerName||"Customer"), assetName:asText(b.assetName||b.name), serialNo:asText(b.serialNo), modelNo:asText(b.modelNo), installationDate:b.installationDate?new Date(b.installationDate):undefined, warrantyUntil:b.warrantyUntil?new Date(b.warrantyUntil):undefined, location:asText(b.location), status:asText(b.status||"active"), notes:asText(b.notes)}); return {ok:true, asset}; }
async function listContracts(req){ const { AmcContractModel }=await scoped(req); return {ok:true, contracts: await AmcContractModel.find({companyId:companyIdFrom(req)}).sort({createdAt:-1}).limit(300).lean()}; }
async function createContract(req){ const { AmcContractModel }=await scoped(req); const b=req.body||{}, companyId=companyIdFrom(req); const contract=await AmcContractModel.create({companyId, contractNo:asText(b.contractNo)||docNo("AMC"), customerId:asText(b.customerId), customerName:asText(b.customerName||"Customer"), assetId:asText(b.assetId), assetName:asText(b.assetName), startDate:b.startDate?new Date(b.startDate):undefined, endDate:b.endDate?new Date(b.endDate):undefined, visitFrequency:asText(b.visitFrequency||"monthly"), contractValue:money(b.contractValue), billingCycle:asText(b.billingCycle||"monthly"), status:asText(b.status||"active"), notes:asText(b.notes)}); return {ok:true, contract}; }
async function listTickets(req){ const { ServiceTicketModel }=await scoped(req); const filter={companyId:companyIdFrom(req)}; if(req.query.status) filter.status=asText(req.query.status); return {ok:true, tickets: await ServiceTicketModel.find(filter).sort({createdAt:-1}).limit(400).lean()}; }
async function createTicket(req){ const { ServiceTicketModel }=await scoped(req); const b=req.body||{}, companyId=companyIdFrom(req); const sla=n(b.slaHours||24); const ticket=await ServiceTicketModel.create({companyId, ticketNo:asText(b.ticketNo)||docNo("TKT"), customerId:asText(b.customerId), customerName:asText(b.customerName||"Customer"), assetId:asText(b.assetId), assetName:asText(b.assetName), subject:asText(b.subject||"Service request"), priority:asText(b.priority||"medium"), slaHours:sla, dueAt:new Date(Date.now()+sla*3600000), assignedToUserId:asText(b.assignedToUserId), assignedToName:asText(b.assignedToName), status:asText(b.assignedToUserId?"assigned":"open"), attachmentUrl:asText(b.attachmentUrl), statusHistory:[statusEntry(asText(b.assignedToUserId?"assigned":"open"), uidFrom(req), "Ticket created")], notes:asText(b.notes)}); return {ok:true, ticket}; }
async function updateTicketStatus(req){ const { ServiceTicketModel }=await scoped(req); const ticket=await ServiceTicketModel.findOne({_id:req.params.id, companyId:companyIdFrom(req)}); if(!ticket) throw new Error("Ticket not found"); ticket.status=asText(req.body?.status||ticket.status); if(req.body?.assignedToUserId){ ticket.assignedToUserId=asText(req.body.assignedToUserId); ticket.assignedToName=asText(req.body.assignedToName); } ticket.statusHistory.push(statusEntry(ticket.status, uidFrom(req), asText(req.body?.notes))); await ticket.save(); return {ok:true, ticket}; }
async function listOrders(req){ const { ServiceOrderModel }=await scoped(req); const filter={companyId:companyIdFrom(req)}; if(req.query.status) filter.status=asText(req.query.status); return {ok:true, orders: await ServiceOrderModel.find(filter).sort({createdAt:-1}).limit(400).lean()}; }
async function createOrder(req){ const { ServiceOrderModel, ServiceTicketModel }=await scoped(req); const b=req.body||{}, companyId=companyIdFrom(req); let ticket=null; if(b.ticketId) ticket=await ServiceTicketModel.findOne({_id:b.ticketId,companyId}).lean(); const lines=(Array.isArray(b.lines)?b.lines:[]).map(normalizeLine); const totals=lineTotals(lines); totals.grandTotal=money(totals.grandTotal+n(b.laborAmount)); const order=await ServiceOrderModel.create({companyId, orderNo:asText(b.orderNo)||docNo("SRV"), ticketId:ticket?._id, ticketNo:ticket?.ticketNo, customerId:asText(b.customerId||ticket?.customerId), customerName:asText(b.customerName||ticket?.customerName||"Customer"), assetId:asText(b.assetId||ticket?.assetId), assetName:asText(b.assetName||ticket?.assetName), technicianId:asText(b.technicianId), technicianName:asText(b.technicianName), serviceType:asText(b.serviceType||"repair"), scheduledAt:b.scheduledAt?new Date(b.scheduledAt):undefined, warehouseId:asText(b.warehouseId), warehouseName:asText(b.warehouseName), laborAmount:money(b.laborAmount), lines, totals, status:asText(b.status||"scheduled"), statusHistory:[statusEntry("scheduled", uidFrom(req), "Service order created")], proofUrl:asText(b.proofUrl), notes:asText(b.notes)}); return {ok:true, order}; }
async function completeOrder(req){ const { ServiceOrderModel, InventoryLedgerModel }=await scoped(req); const companyId=companyIdFrom(req); const order=await ServiceOrderModel.findOne({_id:req.params.id,companyId}); if(!order) throw new Error("Service order not found"); for(const line of order.lines||[]) if(line.productId && n(line.qty)>0) await InventoryLedgerModel.create({companyId, ownerType:"company", ownerId:companyId, warehouseId:order.warehouseId, warehouseName:order.warehouseName, productId:line.productId, productCode:line.productCode, productName:line.productName, batchNo:line.batchNo, movementType:"service_spare_part", direction:"out", qty:n(line.qty), unitCost:money(line.unitCost), totalValue:money(n(line.qty)*n(line.unitCost)), referenceType:"service_order", referenceId:order._id, referenceNo:order.orderNo, postedAt:new Date(), postedByUserId:uidFrom(req)}); order.status=asText(req.body?.status||"completed"); order.completedAt=new Date(); order.proofUrl=asText(req.body?.proofUrl||order.proofUrl); order.statusHistory.push(statusEntry(order.status, uidFrom(req), asText(req.body?.notes||"Service completed"))); await order.save(); return {ok:true, order}; }
async function listTechnicians(req){ const { UserModel }=await scoped(req); return {ok:true, technicians: await UserModel.find({companyId:companyIdFrom(req), $or:[{role:/technician/i},{role:/service/i},{portalType:/technician|service/i}]}).select("_id userId fullName username mobile role portalType").limit(200).lean().catch(()=>[]) }; }
async function printDocument(req){ const { ServiceTicketModel, ServiceOrderModel, AmcContractModel, CustomerAssetModel }=await scoped(req); const companyId=companyIdFrom(req); const type=asText(req.params.type); const id=req.params.id; let doc=null; if(type==="ticket") doc=await ServiceTicketModel.findOne({_id:id,companyId}).lean(); if(type==="order") doc=await ServiceOrderModel.findOne({_id:id,companyId}).lean(); if(type==="contract") doc=await AmcContractModel.findOne({_id:id,companyId}).lean(); if(type==="asset") doc=await CustomerAssetModel.findOne({_id:id,companyId}).lean(); if(!doc) throw new Error("Document not found"); return {ok:true, type, document:doc, printedAt:new Date()}; }
module.exports={overview,listAssets,createAsset,listContracts,createContract,listTickets,createTicket,updateTicketStatus,listOrders,createOrder,completeOrder,listTechnicians,printDocument};
