export const ADMIN_SIDEBAR_MODULES = [
  {
    type: 'group',
    key: 'dashboard',
    title: 'Dashboard',
    children: [
      { title: 'Dashboard Overview', modulePath: '' },
      { title: 'Operations Command Center', modulePath: 'operations' },
      { title: 'Sales KPI', modulePath: 'sales-kpi' },
    ],
  },
  {
    type: 'group',
    key: 'company',
    title: 'Company Management',
    children: [
      { title: 'Add New Company', modulePath: 'companies/add' },
      { title: 'Company List', modulePath: 'companies' },
    ],
  },
  {
    type: 'group',
    key: 'hr',
    title: 'HR & Role Management',
    children: [
      { title: 'Module Overview', modulePath: 'hr' },
      { title: 'Add User', modulePath: 'users/add' },
      { title: 'User List', modulePath: 'users' },
    ],
  },
  {
    type: 'group',
    key: 'products',
    title: 'Products Management',
    children: [
      { title: 'Add New Product', modulePath: 'products/add' },
      { title: 'View Product List', modulePath: 'products' },
      { title: 'Product Barcode List', modulePath: 'products/barcodes' },
      { title: 'Price Change', modulePath: 'products/price-change' },
    ],
  },
  {
    type: 'group',
    key: 'inventory',
    title: 'Warehouse & Inventory',
    children: [
      { title: 'Module Overview', modulePath: 'warehouse-inventory' },
      { title: 'Warehouse Master', modulePath: 'inventory/warehouses' },
    ],
  },
  {
    type: 'group',
    key: 'territory',
    title: 'Territory & Assets',
    children: [
      { title: 'Add Warehouse', modulePath: 'warehouses/add' },
      { title: 'Warehouse List', modulePath: 'warehouses' },
      { title: 'Add Region', modulePath: 'regions/add' },
      { title: 'Region List', modulePath: 'regions' },
      { title: 'Add Zone', modulePath: 'zones/add' },
      { title: 'Zone List', modulePath: 'zones' },
      { title: 'Add Territory', modulePath: 'areas/add' },
      { title: 'Territory List', modulePath: 'areas' },
      { title: 'Add Field', modulePath: 'fields/add' },
      { title: 'Field List', modulePath: 'fields' },
      { title: 'Add Vehicle', modulePath: 'assets/vehicles/add' },
      { title: 'Vehicle List', modulePath: 'assets/vehicles' },
    ],
  },
  {
    type: 'group',
    key: 'orders',
    title: 'Order Management',
    children: [
      { title: 'Module Overview', modulePath: 'order-management' },
      { title: 'Sales Orders', modulePath: 'order-management/sales-orders' },
      { title: 'Order Approvals', modulePath: 'order-management/approvals' },
      { title: 'Pick & Dispatch', modulePath: 'order-management/dispatch' },
      { title: 'Returns & Claims', modulePath: 'order-management/returns' },
    ],
  },
  {
    type: 'group',
    key: 'vehicle-management',
    title: 'Vehicle Management',
    children: [
      { title: 'Module Overview', modulePath: 'vehicle-management' },
      { title: 'Add Vehicle', modulePath: 'vehicle-management/add' },
      { title: 'Vehicle List', modulePath: 'vehicle-management/vehicles' },
      { title: 'Fuel Management', modulePath: 'vehicle-management/fuel-management' },
      { title: 'Vehicle Maintenance', modulePath: 'vehicle-management/maintenance' },
    ],
  },
  {
    type: 'group',
    key: 'account-management',
    title: 'Account Management',
    children: [
      { title: 'Account Detail', modulePath: 'account/manage' },
      { title: 'Loan Detail', modulePath: 'account/loan-detail' },
      { title: 'Payment Management', modulePath: 'finance/payments' },
    ],
  },
  {
    type: 'group',
    key: 'finance',
    title: 'Finance & Accounts',
    children: [
      { title: 'Module Overview', modulePath: 'finance' },
      { title: 'Invoices', modulePath: 'finance/invoices' },
      { title: 'Receipts', modulePath: 'finance/receipts' },
      { title: 'Aging Report', modulePath: 'finance/aging' },
    ],
  },
  {
    type: 'group',
    key: 'expense',
    title: 'Expense Management',
    children: [
      { title: 'Module Overview', modulePath: 'expense' },
      { title: 'AIM – Personal Expense', modulePath: 'expense/personal' },
      { title: 'Daily Expense', modulePath: 'expense/daily' },
      { title: 'Distributor Expense', modulePath: 'expense/distributor' },
    ],
  },
  {
    type: 'group',
    key: 'procurement',
    title: 'Procurement',
    children: [
      { title: 'Module Overview', modulePath: 'procurement' },
      { title: 'Supplier Master', modulePath: 'procurement/suppliers' },
      { title: 'Purchase Orders', modulePath: 'procurement/purchase-orders' },
      { title: 'Goods Receipt (GRN)', modulePath: 'procurement/grn' },
      { title: 'Supplier Payments', modulePath: 'procurement/payments' },
    ],
  },
  {
    type: 'group',
    key: 'logistics',
    title: 'Distribution & Logistics',
    children: [
      { title: 'Module Overview', modulePath: 'logistics' },
      { title: 'Route Planning', modulePath: 'logistics/routes' },
    ],
  },
  {
    type: 'group',
    key: 'quality',
    title: 'Quality & Compliance',
    children: [
      { title: 'Module Overview', modulePath: 'quality' },
      { title: 'Raw Material QC', modulePath: 'quality/raw-material' },
      { title: 'Production QC', modulePath: 'quality/production' },
      { title: 'Finished Goods QC', modulePath: 'quality/finished-goods' },
      { title: 'Final Release QC', modulePath: 'quality/final-release' },
    ],
  },
  { type: 'link', key: 'messages', title: 'Messages', modulePath: 'messages' },
  { type: 'link', key: 'live-tracking', title: 'User Live Tracking', modulePath: 'live-tracking' },
  { type: 'group', key: 'reports', title: 'Reports', children: [
    { title: 'Command Center', modulePath: 'reports' },
  ] },
  { type: 'group', key: 'settings', title: 'Settings', children: [
    { title: 'Account Settings', modulePath: 'settings' },
    { title: 'Change Password', modulePath: 'settings/change-password' },
  ] },
];