export const adminDashboardSearchItems = [
  { title: "Dashboard", href: "/dashboards/admin" },
  { title: "Operations Command Center", href: "/dashboards/admin/operations" },
  { title: "Sales KPI", href: "/dashboards/admin/sales-kpi" },
  { title: "Add New Company", href: "/dashboards/admin/companies/add" },
  { title: "Company List", href: "/dashboards/admin/companies" },
  { title: "Add New Product", href: "/dashboards/admin/products/add" },
  { title: "View Product List", href: "/dashboards/admin/products" },
  { title: "Product Barcode List", href: "/dashboards/admin/products/barcodes" },
  { title: "Price Change", href: "/dashboards/admin/products/price-change" },
  { title: "Warehouse & Inventory Module Overview", href: "/dashboards/admin/warehouse-inventory" },
  { title: "Warehouse Master", href: "/dashboards/admin/inventory/warehouses" },
  { title: "Inventory Ledger", href: "/dashboards/admin/inventory/ledger" },
  { title: "Stock Transfers", href: "/dashboards/admin/inventory/transfers" },
  { title: "Stock Summary", href: "/dashboards/admin/inventory/summary" },
  { title: "Low Stock Alerts", href: "/dashboards/admin/inventory/low-stock" },
  { title: "Add Warehouse", href: "/dashboards/admin/warehouses/add" },
  { title: "Warehouse List", href: "/dashboards/admin/warehouses" },
  { title: "Add Region", href: "/dashboards/admin/regions/add" },
  { title: "Region List", href: "/dashboards/admin/regions" },
  { title: "Add Zone", href: "/dashboards/admin/zones/add" },
  { title: "Zone List", href: "/dashboards/admin/zones" },
  { title: "Add Territory", href: "/dashboards/admin/areas/add" },
  { title: "Territory List", href: "/dashboards/admin/areas" },
  { title: "Add Field", href: "/dashboards/admin/fields/add" },
  { title: "Field List", href: "/dashboards/admin/fields" },
  { title: "Add Vehicle", href: "/dashboards/admin/assets/vehicles/add" },
  { title: "Vehicle List", href: "/dashboards/admin/assets/vehicles" },
  { title: "Order Management Module Overview", href: "/dashboards/admin/order-management" },
  { title: "Sales Orders", href: "/dashboards/admin/order-management/sales-orders" },
  { title: "Order Approvals", href: "/dashboards/admin/order-management/approvals" },
  { title: "Pick & Dispatch", href: "/dashboards/admin/order-management/dispatch" },
  { title: "Returns & Claims", href: "/dashboards/admin/order-management/returns" },
  { title: "Procurement Module Overview", href: "/dashboards/admin/procurement" },
  { title: "Supplier Master", href: "/dashboards/admin/procurement/suppliers" },
  { title: "Purchase Orders", href: "/dashboards/admin/procurement/purchase-orders" },
  { title: "Goods Receipt (GRN)", href: "/dashboards/admin/procurement/grn" },
  { title: "Supplier Payments", href: "/dashboards/admin/procurement/payments" },
  { title: "Distribution & Logistics Module Overview", href: "/dashboards/admin/logistics" },
  { title: "Route Planning", href: "/dashboards/admin/logistics/routes" },
  { title: "Dispatch & Delivery", href: "/dashboards/admin/logistics/dispatch" },
  { title: "Vehicle Assignment", href: "/dashboards/admin/assets/vehicles" },
  { title: "Finance & Accounts Module Overview", href: "/dashboards/admin/finance" },
  { title: "Invoices", href: "/dashboards/admin/finance/invoices" },
  { title: "Receipts", href: "/dashboards/admin/finance/receipts" },
  { title: "Aging Report", href: "/dashboards/admin/finance/aging" },
  { title: "HR & Role Management Module Overview", href: "/dashboards/admin/hr" },
  { title: "Add User", href: "/dashboards/admin/users/add" },
  { title: "User List", href: "/dashboards/admin/users" },
  { title: "Quality & Compliance Module Overview", href: "/dashboards/admin/quality" },
  { title: "Raw Material QC", href: "/dashboards/admin/quality/raw-material" },
  { title: "Production QC", href: "/dashboards/admin/quality/production" },
  { title: "Finished Goods QC", href: "/dashboards/admin/quality/finished-goods" },
  { title: "Final Release QC", href: "/dashboards/admin/quality/final-release" },
  { title: "Add Expense", href: "/dashboards/admin/expense/add" },
  { title: "View Expense List", href: "/dashboards/admin/expense" },
  { title: "Account Management", href: "/dashboards/admin/account/manage" },
  { title: "Messages", href: "/dashboards/admin/messages" },
  { title: "User Live Tracking", href: "/dashboards/admin/live-tracking" },
  { title: "Reports", href: "/dashboards/admin/reports" },
  { title: "Settings", href: "/dashboards/admin/settings" },
  { title: "Change Password", href: "/dashboards/admin/settings/change-password" },
];

const commonUserLinks = [
  { title: "Dashboard Home", href: "/dashboards" },
];


export const userDashboardSearchItems = {
  ceo: [{ title: "CEO Dashboard", href: "/dashboards/ceo" }, ...commonUserLinks],
  manageDirector: [{ title: "Managing Director Dashboard", href: "/dashboards/manageDirector" }, ...commonUserLinks],
  warehouseManager: [{ title: "Warehouse Manager Dashboard", href: "/dashboards/warehouseManager" }, ...commonUserLinks],
  accountOfficer: [{ title: "Account Officer Dashboard", href: "/dashboards/accountOfficer" }, ...commonUserLinks],
  cashier: [{ title: "Cashier Dashboard", href: "/dashboards/cashier" }, ...commonUserLinks],
  hrAssistant: [{ title: "HR Assistant Dashboard", href: "/dashboards/hrAssistant" }, ...commonUserLinks],
  kpo: [{ title: "KPO Dashboard", href: "/dashboards/kpo" }, ...commonUserLinks],
  brandManager: [{ title: "Brand Manager Dashboard", href: "/dashboards/brandManager" }, { title: "Return Stock", href: "/dashboards/brandManager/return-stock" }, { title: "Messages", href: "/dashboards/brandManager/messages" }, { title: "Account Settings", href: "/dashboards/brandManager/settings" }, { title: "Change Password", href: "/dashboards/brandManager/settings/change-password" }, ...commonUserLinks],
  nationalSM: [{ title: "National Sale Manager Dashboard", href: "/dashboards/nationalSM" }, ...commonUserLinks],
  regionalSM: [{ title: "Regional Sale Manager Dashboard", href: "/dashboards/regionalSM" }, ...commonUserLinks],
  zoneSM: [{ title: "Zone Sale Manager Dashboard", href: "/dashboards/zoneSM" }, ...commonUserLinks],
  territorySM: [{ title: "Territory Sale Manager Dashboard", href: "/dashboards/territorySM" }, ...commonUserLinks],
  distributor: [{ title: "Distributor Dashboard", href: "/dashboards/distributor" }, { title: "Return Stock", href: "/dashboards/distributor/return-stock" }, { title: "Messages", href: "/dashboards/distributor/messages" }, { title: "Account Settings", href: "/dashboards/distributor/settings" }, { title: "Change Password", href: "/dashboards/distributor/settings/change-password" }, ...commonUserLinks],
  fieldSM: [{ title: "Field Sale Manager Dashboard", href: "/dashboards/fieldSM" }, ...commonUserLinks],
  orderBooker: [{ title: "Order Booker Dashboard", href: "/dashboards/orderBooker" }, ...commonUserLinks],
  salesman: [{ title: "Salesman Dashboard", href: "/dashboards/salesman" }, ...commonUserLinks],
  deliveryBoy: [{ title: "Delivery Boy Dashboard", href: "/dashboards/deliveryBoy" }, ...commonUserLinks],
  customer: [{ title: "Customer Dashboard", href: "/dashboards/customer" }, ...commonUserLinks],
};