export const adminDashboardSearchItems = [
  { title: "Dashboard", href: "/dashboards/admin" },
  { title: "Operations Command Center", href: "/dashboards/admin/operations" },
  { title: "Sales KPI", href: "/dashboards/admin/sales-kpi" },
  { title: "Add New Company", href: "/dashboards/admin/companies/add" },
  { title: "Company List", href: "/dashboards/admin/companies" },
  { title: "Add New Product", href: "/dashboards/admin/products/add" },
  { title: "View Product List", href: "/dashboards/admin/products" },
  { title: "Product Barcode List", href: "/dashboards/admin/products/barcodes" },
  { title: "Price Change", href: "/dashboards/admin/products/price-change" },
  { title: "Warehouse & Inventory Module Overview", href: "/dashboards/admin/warehouse-inventory" },
  { title: "Warehouse Master", href: "/dashboards/admin/inventory/warehouses" },
  { title: "Inventory Ledger", href: "/dashboards/admin/inventory/ledger" },
  { title: "Stock Transfers", href: "/dashboards/admin/inventory/transfers" },
  { title: "Stock Summary", href: "/dashboards/admin/inventory/summary" },
  { title: "Low Stock Alerts", href: "/dashboards/admin/inventory/low-stock" },
  { title: "Add Warehouse", href: "/dashboards/admin/warehouses/add" },
  { title: "Warehouse List", href: "/dashboards/admin/warehouses" },
  { title: "Add Region", href: "/dashboards/admin/regions/add" },
  { title: "Region List", href: "/dashboards/admin/regions" },
  { title: "Add Zone", href: "/dashboards/admin/zones/add" },
  { title: "Zone List", href: "/dashboards/admin/zones" },
  { title: "Add Territory", href: "/dashboards/admin/areas/add" },
  { title: "Territory List", href: "/dashboards/admin/areas" },
  { title: "Add Field", href: "/dashboards/admin/fields/add" },
  { title: "Field List", href: "/dashboards/admin/fields" },
  { title: "Add Vehicle", href: "/dashboards/admin/assets/vehicles/add" },
  { title: "Vehicle List", href: "/dashboards/admin/assets/vehicles" },
  { title: "Order Management Module Overview", href: "/dashboards/admin/order-management" },
  { title: "Sales Orders", href: "/dashboards/admin/order-management/sales-orders" },
  { title: "Order Approvals", href: "/dashboards/admin/order-management/approvals" },
  { title: "Pick & Dispatch", href: "/dashboards/admin/order-management/dispatch" },
  { title: "Returns & Claims", href: "/dashboards/admin/order-management/returns" },
  { title: "Account Management", href: "/dashboards/admin/account/manage" },
  { title: "Procurement Module Overview", href: "/dashboards/admin/procurement" },
  { title: "Supplier Master", href: "/dashboards/admin/procurement/suppliers" },
  { title: "Purchase Orders", href: "/dashboards/admin/procurement/purchase-orders" },
  { title: "Goods Receipt (GRN)", href: "/dashboards/admin/procurement/grn" },
  { title: "Supplier Payments", href: "/dashboards/admin/procurement/payments" },
  { title: "Distribution & Logistics Module Overview", href: "/dashboards/admin/logistics" },
  { title: "Route Planning", href: "/dashboards/admin/logistics/routes" },
  { title: "Dispatch & Delivery", href: "/dashboards/admin/logistics/dispatch" },
  { title: "Vehicle Assignment", href: "/dashboards/admin/assets/vehicles" },
  { title: "Finance & Accounts Module Overview", href: "/dashboards/admin/finance" },
  { title: "Invoices", href: "/dashboards/admin/finance/invoices" },
  { title: "Receipts", href: "/dashboards/admin/finance/receipts" },
  { title: "Aging Report", href: "/dashboards/admin/finance/aging" },
  { title: "Add Expense", href: "/dashboards/admin/expense/add" },
  { title: "View Expense List", href: "/dashboards/admin/expense" },
  { title: "HR & Role Management Module Overview", href: "/dashboards/admin/hr" },
  { title: "Add User", href: "/dashboards/admin/users/add" },
  { title: "User List", href: "/dashboards/admin/users" },
  { title: "Quality & Compliance Module Overview", href: "/dashboards/admin/quality" },
  { title: "Raw Material QC", href: "/dashboards/admin/quality/raw-material" },
  { title: "Production QC", href: "/dashboards/admin/quality/production" },
  { title: "Finished Goods QC", href: "/dashboards/admin/quality/finished-goods" },
  { title: "Final Release QC", href: "/dashboards/admin/quality/final-release" },
  { title: "Messages", href: "/dashboards/admin/messages" },
  { title: "User Live Tracking", href: "/dashboards/admin/live-tracking" },
  { title: "Reports", href: "/dashboards/admin/reports" },
  { title: "Settings", href: "/dashboards/admin/settings" },
  { title: "Change Password", href: "/dashboards/admin/settings/change-password" },
];

export const userDashboardSearchItems = {
  ceo: [{ title: "Dashboard", href: "/dashboards/ceo" }],
  manageDirector: [{ title: "Dashboard", href: "/dashboards/manageDirector" }],
  warehouseManager: [
    { title: "Dashboard", href: "/dashboards/warehouseManager" },
    { title: "Warehouse & Inventory", href: "/dashboards/warehouseManager/warehouse-inventory" },
    { title: "Order Management", href: "/dashboards/warehouseManager/order-management" },
    { title: "Payment Management", href: "/dashboards/warehouseManager/payments" },
    { title: "Primary Payment", href: "/dashboards/warehouseManager/payments/primary" },
    { title: "Secondary Payment", href: "/dashboards/warehouseManager/payments/secondary" },
  ],
  accountOfficer: [{ title: "Dashboard", href: "/dashboards/accountOfficer" }],
  cashier: [{ title: "Dashboard", href: "/dashboards/cashier" }],
  hrAssistant: [{ title: "Dashboard", href: "/dashboards/hrAssistant" }],
  kpo: [{ title: "Dashboard", href: "/dashboards/kpo" }],
  brandManager: [
    { title: "Dashboard", href: "/dashboards/brandManager" },
    { title: "Primary Order Request", href: "/dashboards/brandManager/primary-order-request" },
    { title: "Primary Sale Orders", href: "/dashboards/brandManager/orders" },
    { title: "Return Stock", href: "/dashboards/brandManager/return-stock" },
    { title: "Messages", href: "/dashboards/brandManager/messages" },
    { title: "Account Settings", href: "/dashboards/brandManager/settings" },
    { title: "Change Password", href: "/dashboards/brandManager/settings/change-password" },
  ],
  nationalSM: [{ title: "Dashboard", href: "/dashboards/nationalSM" }],
  regionalSM: [{ title: "Dashboard", href: "/dashboards/regionalSM" }],
  zoneSM: [{ title: "Dashboard", href: "/dashboards/zoneSM" }],
  territorySM: [{ title: "Dashboard", href: "/dashboards/territorySM" }],
  distributor: [
    { title: "Dashboard", href: "/dashboards/distributor" },
    { title: "Reports", href: "/dashboards/distributor/reports" },
    { title: "Expense", href: "/dashboards/distributor/expense" },
    { title: "Receipts", href: "/dashboards/distributor/receipts" },
    { title: "Payments", href: "/dashboards/distributor/payments" },
    { title: "Primary Payments (Received)", href: "/dashboards/distributor/payments/primary" },
    { title: "Secondary Payments (Paid Back)", href: "/dashboards/distributor/payments/secondary" },
    { title: "Primary Order Request", href: "/dashboards/distributor/primary-order-request" },
    { title: "Secondary Orders", href: "/dashboards/distributor/orders" },
    { title: "Return Stock", href: "/dashboards/distributor/return-stock" },
    { title: "Messages", href: "/dashboards/distributor/messages" },
    { title: "Live Tracking", href: "/dashboards/distributor/live-tracking" },
    { title: "Account Settings", href: "/dashboards/distributor/settings" },
    { title: "Change Password", href: "/dashboards/distributor/settings/change-password" },
  ],
  fieldSM: [{ title: "Dashboard", href: "/dashboards/fieldSM" }],
  orderBooker: [{ title: "Dashboard", href: "/dashboards/orderBooker" }, { title: "Secondary Sale Requests", href: "/dashboards/orderBooker/orders" }, { title: "Receipts", href: "/dashboards/orderBooker/receipts" }],
  salesman: [{ title: "Dashboard", href: "/dashboards/salesman" }, { title: "Deliveries", href: "/dashboards/salesman/orders" }],
  deliveryBoy: [{ title: "Dashboard", href: "/dashboards/deliveryBoy" }, { title: "Proof of Delivery", href: "/dashboards/deliveryBoy/orders" }],
  customer: [
    { title: "Dashboard", href: "/dashboards/customer" },
    { title: "Order Requests", href: "/dashboards/customer/orders" },
    { title: "Receipts", href: "/dashboards/customer/receipts" },
    { title: "Account Settings", href: "/dashboards/customer/settings" },
    { title: "Change Password", href: "/dashboards/customer/settings/change-password" },
  ],
  supplier: [{ title: "Dashboard", href: "/dashboards/supplier" }],
  vendor: [{ title: "Dashboard", href: "/dashboards/vendor" }],
};
