const DEFAULT_PORTAL_MODULES = [
  ["dashboard", "Dashboard", "Core", "/portals", "LayoutDashboard", 1, ["view"], true],
  ["companies", "Companies", "Core", "/portals/companies", "Building2", 10, ["view", "create", "edit", "delete"], false],
  ["erp-templates", "ERP Templates", "Core", "/portals/erp-templates", "Layers", 12, ["view", "create", "edit", "delete"], false],
  ["roles", "Roles & Permissions", "Core", "/portals/roles", "ShieldCheck", 14, ["view", "create", "edit", "delete", "assign"], false],
  ["users", "Users", "Core", "/portals/users", "Users", 16, ["view", "create", "edit", "delete", "assign"], false],
  ["territory", "Territory", "Territory", "/portals/territory", "Map", 30, ["view", "create", "edit", "delete"], true],
  ["products", "Products", "Inventory", "/portals/products", "Package", 40, ["view", "create", "edit", "delete", "print"], false],
  ["procurement", "Procurement", "Supply Chain", "/portals/procurement", "ShoppingBag", 50, ["view", "create", "edit", "approve", "print"], false],
  ["inventory", "Inventory", "Inventory", "/portals/inventory", "Boxes", 60, ["view", "create", "edit", "approve", "export"], true],
  ["warehouse", "Warehouse", "Inventory", "/portals/warehouse", "Warehouse", 70, ["view", "create", "edit", "approve", "print"], true],
  ["primary-orders", "Primary Sales", "Sales", "/portals/sales/primary-orders", "ArrowRightLeft", 80, ["view", "create", "edit", "approve", "print"], true],
  ["secondary-orders", "Secondary Sales", "Sales", "/portals/sales/secondary-orders", "ShoppingCart", 90, ["view", "create", "edit", "approve", "print"], true],
  ["customers", "Customers", "Sales", "/portals/customers", "Store", 100, ["view", "create", "edit", "delete"], true],
  ["finance", "Finance", "Finance", "/portals/finance", "Wallet", 110, ["view", "create", "edit", "approve", "export", "print"], false],
  ["receipts", "Receipts", "Finance", "/portals/finance/receipts", "Receipt", 112, ["view", "create", "edit", "print"], true],
  ["returns", "Returns", "Operations", "/portals/returns", "Undo2", 120, ["view", "create", "edit", "approve", "print"], false],
  ["fleet", "Fleet", "Logistics", "/portals/fleet", "Truck", 130, ["view", "create", "edit", "delete", "approve"], false],
  ["dispatches", "Dispatches", "Logistics", "/portals/logistics/dispatches", "PackageCheck", 132, ["view", "create", "edit", "approve", "print"], true],
  ["deliveries", "Deliveries", "Logistics", "/portals/deliveries", "Navigation", 134, ["view", "edit", "print"], true],
  ["live-tracking", "Live Tracking", "Logistics", "/portals/live-tracking", "MapPin", 140, ["view", "track"], true],
  ["messages", "Messages", "Communication", "/portals/messages", "MessageSquare", 150, ["view", "create", "edit"], true],
  ["reports", "Reports", "Reports", "/portals/reports", "BarChart3", 160, ["view", "export", "print"], false],
  ["settings", "Settings", "Core", "/portals/settings", "Settings", 999, ["view", "edit"], true],
].map(([key, name, category, path, icon, order, actions, mobileEnabled]) => ({ key, name, category, path, icon, order, actions, mobileEnabled, webEnabled: true, allowedErpTemplates: ["distribution_erp", "trading_erp", "manufacturing_erp", "retail_pos_erp", "service_erp", "custom_erp"] }));
module.exports = { DEFAULT_PORTAL_MODULES };
