module.exports = [
  { key: "dashboard", name: "Dashboard", path: "/portals", category: "Home", webEnabled: true, mobileEnabled: true },
  { key: "system-admin", name: "System Admin", path: "/portals/system-admin", category: "SaaS Control", webEnabled: true, mobileEnabled: false },
  { key: "system-admin-companies", name: "Client Companies", path: "/portals/system-admin/companies", category: "SaaS Control", webEnabled: true, mobileEnabled: false },
  { key: "system-admin-users", name: "System Users", path: "/portals/system-admin/users", category: "SaaS Control", webEnabled: true, mobileEnabled: false },
  { key: "subscription-plans", name: "Subscription Plans", path: "/portals/system-admin/subscriptions", category: "SaaS Control", webEnabled: true, mobileEnabled: false },
  { key: "module-controls", name: "Module Controls", path: "/portals/system-admin/modules", category: "SaaS Control", webEnabled: true, mobileEnabled: false },
  { key: "companies", name: "Companies", path: "/portals/companies", category: "Setup", webEnabled: true, mobileEnabled: false },
  { key: "erp-templates", name: "ERP Templates", path: "/portals/erp-templates", category: "Setup", webEnabled: true, mobileEnabled: false },
  { key: "roles", name: "Roles & Permissions", path: "/portals/roles", category: "Setup", webEnabled: true, mobileEnabled: false },
  { key: "users", name: "Users", path: "/portals/users", category: "Setup", webEnabled: true, mobileEnabled: true },
  { key: "settings", name: "Settings", path: "/portals/settings", category: "Setup", webEnabled: true, mobileEnabled: false },
  { key: "products", name: "Products", path: "/portals/products", category: "Master Data", webEnabled: true, mobileEnabled: false },
  { key: "suppliers", name: "Suppliers", path: "/portals/master-data/suppliers", category: "Master Data", webEnabled: true, mobileEnabled: false },
  { key: "customers", name: "Customers", path: "/portals/customers", category: "Master Data", webEnabled: true, mobileEnabled: true },
  { key: "warehouses", name: "Warehouses", path: "/portals/master-data/warehouses", category: "Master Data", webEnabled: true, mobileEnabled: false },
  { key: "territory", name: "Territory", path: "/portals/territory", category: "Master Data", webEnabled: true, mobileEnabled: false },
  { key: "regions", name: "Regions", path: "/portals/master-data/regions", category: "Master Data", webEnabled: true, mobileEnabled: false },
  { key: "zones", name: "Zones", path: "/portals/master-data/zones", category: "Master Data", webEnabled: true, mobileEnabled: false },
  { key: "areas", name: "Territories / Areas", path: "/portals/master-data/areas", category: "Master Data", webEnabled: true, mobileEnabled: false },
  { key: "fields", name: "Fields / Beats", path: "/portals/master-data/fields", category: "Master Data", webEnabled: true, mobileEnabled: false },
  { key: "sales-quotations", name: "Sales Quotations", path: "/portals/sales/quotations", category: "Sales", webEnabled: true, mobileEnabled: false },
  { key: "primary-sales-orders", name: "Primary Sales", path: "/portals/sales/primary-orders", category: "Sales", webEnabled: true, mobileEnabled: true },
  { key: "secondary-sales-orders", name: "Secondary Sales", path: "/portals/sales/secondary-orders", category: "Sales", webEnabled: true, mobileEnabled: true },
  { key: "customer-orders", name: "Customer Orders", path: "/portals/customers/orders", category: "Sales", webEnabled: true, mobileEnabled: true },
  { key: "customer-billing", name: "Customer Billing", path: "/portals/customer/billing", category: "Sales", webEnabled: true, mobileEnabled: true },
  { key: "returns", name: "Returns", path: "/portals/returns", category: "Sales", webEnabled: true, mobileEnabled: true },
  { key: "procurement", name: "Procurement", path: "/portals/procurement", category: "Purchase", webEnabled: true, mobileEnabled: false },
  { key: "purchase-requests", name: "Purchase Requests", path: "/portals/procurement/purchase-requests", category: "Purchase", webEnabled: true, mobileEnabled: false },
  { key: "purchase-orders", name: "Purchase Orders", path: "/portals/procurement/purchase-orders", category: "Purchase", webEnabled: true, mobileEnabled: false },
  { key: "supplier-payments", name: "Supplier Payments", path: "/portals/procurement/payments", category: "Purchase", webEnabled: true, mobileEnabled: false },
  { key: "inventory", name: "Inventory", path: "/portals/inventory", category: "Inventory", webEnabled: true, mobileEnabled: true },
  { key: "warehouse", name: "Warehouse", path: "/portals/warehouse", category: "Inventory", webEnabled: true, mobileEnabled: true },
  { key: "goods-receipts", name: "Goods Receipts", path: "/portals/warehouse/goods-receipts", category: "Inventory", webEnabled: true, mobileEnabled: true },
  { key: "finance", name: "Finance", path: "/portals/finance", category: "Finance", webEnabled: true, mobileEnabled: false },
  { key: "receipts", name: "Receipts", path: "/portals/finance/receipts", category: "Finance", webEnabled: true, mobileEnabled: true },
  { key: "payments", name: "Payments", path: "/portals/finance/payments", category: "Finance", webEnabled: true, mobileEnabled: false },
  { key: "expenses", name: "Expenses", path: "/portals/expenses", category: "Finance", webEnabled: true, mobileEnabled: true },
  { key: "loans", name: "Loans", path: "/portals/loans", category: "Finance", webEnabled: true, mobileEnabled: false },
  { key: "operations", name: "Operations Center", path: "/portals/operations", category: "Logistics", webEnabled: true, mobileEnabled: false },
  { key: "fleet", name: "Fleet", path: "/portals/fleet", category: "Logistics", webEnabled: true, mobileEnabled: false },
  { key: "dispatches", name: "Dispatches", path: "/portals/logistics/dispatches", category: "Logistics", webEnabled: true, mobileEnabled: true },
  { key: "deliveries", name: "Deliveries", path: "/portals/deliveries", category: "Logistics", webEnabled: true, mobileEnabled: true },
  { key: "live-tracking", name: "Live Tracking", path: "/portals/live-tracking", category: "Logistics", webEnabled: true, mobileEnabled: true },
  { key: "notifications", name: "Notifications", path: "/portals/notifications", category: "Communication", webEnabled: true, mobileEnabled: true },
  { key: "reports", name: "Reports", path: "/portals/reports", category: "Reports", webEnabled: true, mobileEnabled: true },
  { key: "retail-pos", name: "Retail POS", path: "/portals/retail-pos", category: "Retail POS", webEnabled: true, mobileEnabled: true },
  { key: "manufacturing", name: "Manufacturing", path: "/portals/manufacturing", category: "Manufacturing", webEnabled: true, mobileEnabled: false },
  { key: "service", name: "Service ERP", path: "/portals/service", category: "Service", webEnabled: true, mobileEnabled: true },
  { key: "trading", name: "Trading/Import", path: "/portals/trading", category: "Trading", webEnabled: true, mobileEnabled: false },
];
