import { MODULE_BY_KEY, findModuleByPath } from "./moduleCatalog";

export const CANONICAL_PORTAL_ROUTES = {
  "/portals":"dashboard",
  "/portals/companies":"companies",
  "/portals/erp-templates":"erp-templates",
  "/portals/roles":"roles",
  "/portals/users":"users",
  "/portals/territory":"territory",
  "/portals/products":"products",
  "/portals/procurement":"procurement",
  "/portals/procurement/purchase-orders":"purchase-orders",
  "/portals/procurement/payments":"supplier-payments",
  "/portals/inventory":"inventory",
  "/portals/warehouse":"warehouse",
  "/portals/warehouse/goods-receipts":"goods-receipts",
  "/portals/sales/primary-orders":"primary-sales-orders",
  "/portals/sales/secondary-orders":"secondary-sales-orders",
  "/portals/customers":"customers",
  "/portals/customers/orders":"customer-orders",
  "/portals/finance":"finance",
  "/portals/finance/receipts":"receipts",
  "/portals/finance/payments":"payments",
  "/portals/expenses":"expenses",
  "/portals/loans":"loans",
  "/portals/returns":"returns",
  "/portals/fleet":"fleet",
  "/portals/logistics/dispatches":"dispatches",
  "/portals/deliveries":"deliveries",
  "/portals/live-tracking":"live-tracking",
  "/portals/messages":"messages",
  "/portals/reports":"reports",
  "/portals/settings":"settings"
};

export const LEGACY_PORTAL_ALIASES = {
  "/portals/admin":"/portals",
  "/portals/admin/users":"/portals/users",
  "/portals/admin/companies":"/portals/companies",
  "/portals/admin/module-access":"/portals/roles",
  "/portals/admin/regions":"/portals/territory",
  "/portals/admin/zones":"/portals/territory",
  "/portals/admin/areas":"/portals/territory",
  "/portals/admin/fields":"/portals/territory",
  "/portals/admin/products":"/portals/products",
  "/portals/admin/procurement":"/portals/procurement",
  "/portals/admin/procurement/purchase-orders":"/portals/procurement/purchase-orders",
  "/portals/admin/procurement/payments":"/portals/procurement/payments",
  "/portals/admin/procurement/grn":"/portals/warehouse/goods-receipts",
  "/portals/admin/warehouse-inventory":"/portals/warehouse",
  "/portals/admin/warehouses":"/portals/warehouse",
  "/portals/admin/order-management":"/portals/sales/primary-orders",
  "/portals/admin/order-management/sales-orders":"/portals/sales/primary-orders",
  "/portals/admin/finance":"/portals/finance",
  "/portals/admin/expense":"/portals/expenses",
  "/portals/admin/vehicle-management":"/portals/fleet",
  "/portals/admin/logistics":"/portals/logistics/dispatches",
  "/portals/admin/live-tracking":"/portals/live-tracking",
  "/portals/admin/messages":"/portals/messages",
  "/portals/admin/reports":"/portals/reports",
  "/portals/admin/settings":"/portals/settings",
  "/portals/distributor":"/portals",
  "/portals/distributor/orders":"/portals/sales/secondary-orders",
  "/portals/distributor/primary-order-request":"/portals/sales/primary-orders",
  "/portals/distributor/customer-invoices":"/portals/customers/orders",
  "/portals/distributor/receipts":"/portals/finance/receipts",
  "/portals/distributor/payments":"/portals/finance/payments",
  "/portals/distributor/accounts":"/portals/finance",
  "/portals/distributor/inventory":"/portals/inventory",
  "/portals/distributor/stock-received":"/portals/warehouse/goods-receipts",
  "/portals/distributor/return-stock":"/portals/returns",
  "/portals/distributor/damage-expiry":"/portals/returns",
  "/portals/distributor/live-tracking":"/portals/live-tracking",
  "/portals/distributor/users":"/portals/users",
  "/portals/distributor/messages":"/portals/messages",
  "/portals/distributor/reports":"/portals/reports",
  "/portals/distributor/settings":"/portals/settings",
  "/portals/salesman":"/portals",
  "/portals/salesman/orders":"/portals/sales/secondary-orders",
  "/portals/salesman/customers":"/portals/customers",
  "/portals/salesman/collections":"/portals/finance/receipts",
  "/portals/salesman/deliveries":"/portals/deliveries",
  "/portals/orderBooker":"/portals",
  "/portals/orderBooker/orders":"/portals/sales/secondary-orders",
  "/portals/orderBooker/customers":"/portals/customers",
  "/portals/orderBooker/collections":"/portals/finance/receipts",
  "/portals/warehouseManager":"/portals/warehouse",
  "/portals/warehouseManager/orders":"/portals/logistics/dispatches",
  "/portals/warehouseManager/goods-receipts":"/portals/warehouse/goods-receipts",
  "/portals/warehouseManager/warehouse-inventory":"/portals/warehouse",
  "/portals/warehouseManager/damage-expiry":"/portals/returns",
  "/portals/warehouseManager/payments":"/portals/finance/payments",
  "/portals/deliveryBoy":"/portals/deliveries",
  "/portals/deliveryBoy/orders":"/portals/deliveries",
  "/portals/deliveryBoy/dispatches":"/portals/logistics/dispatches",
  "/portals/deliveryBoy/tracking":"/portals/live-tracking",
  "/portals/customer":"/portals/customers",
  "/portals/customer/orders":"/portals/customers/orders",
  "/portals/customer/receipts":"/portals/finance/receipts",
  "/portals/customer/returns":"/portals/returns",
  "/portals/customer/settings":"/portals/settings",
  "/portals/supplier":"/portals/procurement",
  "/portals/supplier/primary-orders":"/portals/procurement/purchase-orders",
  "/portals/supplier/messages":"/portals/messages",
  "/portals/supplier/settings":"/portals/settings",
  "/portals/brandManager":"/portals/sales/primary-orders",
  "/portals/brandManager/primary-order-request":"/portals/sales/primary-orders",
  "/portals/brandManager/return-stock":"/portals/returns",
  "/portals/brandManager/messages":"/portals/messages"
};

export function normalizePortalPath(pathname="/portals") {
  const clean=pathname.replace(/\/$/,"")||"/portals";
  return LEGACY_PORTAL_ALIASES[clean]||clean;
}

export function getPortalRoute(pathname="/portals") {
  const canonicalPath=normalizePortalPath(pathname);
  const key=CANONICAL_PORTAL_ROUTES[canonicalPath];
  const module=key?MODULE_BY_KEY[key]:findModuleByPath(canonicalPath);
  return { pathname, canonicalPath, moduleKey:key||module?.key||"dashboard", title:module?.name||"Rawyan ERP", module:module||MODULE_BY_KEY.dashboard, isLegacyAlias:pathname.replace(/\/$/,"")!==canonicalPath };
}

export default CANONICAL_PORTAL_ROUTES;
