const express = require("express");
const { requireAuth } = require("../../utils/auth");
const controller = require("./userAccess.controller");
const router = express.Router();
router.get("/users", requireAuth, controller.listUsers);
router.get("/users/:id", requireAuth, controller.getUser);
router.patch("/users/:id/role", requireAuth, controller.assignRole);
router.patch("/users/:id/access", requireAuth, controller.updateAccess);
router.patch("/users/:id/status", requireAuth, controller.setStatus);
module.exports = router;
