"use client";

import { useEffect, useMemo, useState } from "react";
import AdminShell from "../../components/AdminShell";
import { apiFetch } from "../../../../lib/api";

const METHODS = [["cash", "Cash"], ["bank_transfer", "Bank Transfer"], ["cheque", "Cheque"], ["online", "Online"]];
const baseLoan = { partyName: "", partyType: "Individual", phone: "", cnicNtn: "", principalAmount: "", loanDate: new Date().toISOString().slice(0, 10), dueDate: "", sourceAccountId: "", paymentMethod: "cash", referenceNo: "", notes: "", attachmentUrl: "" };
const baseReturn = { loanId: "", amount: "", paymentDate: new Date().toISOString().slice(0, 10), accountId: "", method: "cash", referenceNo: "", notes: "", attachmentUrl: "" };

export default function LoanDetailPage() {
  const [tab, setTab] = useState("received");
  const [accounts, setAccounts] = useState([]);
  const [loans, setLoans] = useState([]);
  const [summary, setSummary] = useState(null);
  const [loanForm, setLoanForm] = useState(baseLoan);
  const [returnForm, setReturnForm] = useState(baseReturn);
  const [selectedLoan, setSelectedLoan] = useState(null);
  const [loanDetail, setLoanDetail] = useState(null);
  const openLoans = useMemo(() => loans.filter((l) => l.status === "open" && l.remainingAmount > 0), [loans]);

  async function load() {
    const [a, l, s] = await Promise.all([apiFetch("/accounts"), apiFetch(`/loans?loanType=${tab}`), apiFetch("/loans/summary")]);
    setAccounts(a.accounts || []); setLoans(l.loans || []); setSummary(s.summary || null);
  }
  async function loadDetail(id) { if (!id) return setLoanDetail(null); const d = await apiFetch(`/loans/${id}`); setLoanDetail(d); }
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [tab]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (selectedLoan) loadDetail(selectedLoan); }, [selectedLoan]);

  async function createLoan(e) {
    e.preventDefault();
    await apiFetch("/loans", { method: "POST", body: { ...loanForm, loanType: tab, principalAmount: Number(loanForm.principalAmount || 0) } });
    setLoanForm(baseLoan); await load();
  }
  async function createReturn(e) {
    e.preventDefault();
    await apiFetch(`/loans/${returnForm.loanId}/payments`, { method: "POST", body: { ...returnForm, amount: Number(returnForm.amount || 0) } });
    setReturnForm(baseReturn); await load(); if (selectedLoan) await loadDetail(selectedLoan);
  }

  return <AdminShell title="Loan Detail" user={null}><div className="space-y-5">
    <div className="rounded-2xl bg-white border shadow-sm p-5"><div className="text-xl font-semibold">Loan Detail</div><div className="mt-4 grid md:grid-cols-4 gap-3 text-sm"><Card title="Received Loans (Open)" value={summary ? Number(summary.totalReceivedLoansOpenAmount || 0).toLocaleString() : "0"} /><Card title="Given Loans (Open)" value={summary ? Number(summary.totalGivenLoansOpenAmount || 0).toLocaleString() : "0"} /><Card title="Overdue Loans" value={summary ? summary.overdueLoansCount : 0} /><Card title="Upcoming Due (7d)" value={summary ? summary.upcomingDueCount : 0} /></div><div className="mt-4 inline-flex rounded-xl border bg-zinc-50 p-1"><button onClick={() => setTab("received")} className={`px-4 py-2 rounded-lg text-sm ${tab === "received" ? "bg-white shadow font-semibold" : "text-zinc-600"}`}>Received Loan</button><button onClick={() => setTab("given")} className={`px-4 py-2 rounded-lg text-sm ${tab === "given" ? "bg-white shadow font-semibold" : "text-zinc-600"}`}>Given Loan</button></div></div>

    <Section title={tab === "received" ? "Create Received Loan" : "Create Given Loan"}><form onSubmit={createLoan} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field required label={tab === "received" ? "Lender Name" : "Borrower Name"} value={loanForm.partyName} onChange={(v) => setLoanForm((s) => ({ ...s, partyName: v }))} /><Field label="Type" value={loanForm.partyType} onChange={(v) => setLoanForm((s) => ({ ...s, partyType: v }))} /><Field label="Phone" value={loanForm.phone} onChange={(v) => setLoanForm((s) => ({ ...s, phone: v }))} /><Field label="CNIC/NTN" value={loanForm.cnicNtn} onChange={(v) => setLoanForm((s) => ({ ...s, cnicNtn: v }))} /><Field type="number" required label="Loan Amount (PKR)" value={loanForm.principalAmount} onChange={(v) => setLoanForm((s) => ({ ...s, principalAmount: v }))} /><Field type="date" required label="Loan Date" value={loanForm.loanDate} onChange={(v) => setLoanForm((s) => ({ ...s, loanDate: v }))} /><Field type="date" label="Due Date" value={loanForm.dueDate} onChange={(v) => setLoanForm((s) => ({ ...s, dueDate: v }))} /><Select required label="Account" value={loanForm.sourceAccountId} onChange={(v) => setLoanForm((s) => ({ ...s, sourceAccountId: v }))} options={accounts.map((a) => [a._id, `${a.accountName} (${a.currency})`])} /><Select label="Payment Method" value={loanForm.paymentMethod} onChange={(v) => setLoanForm((s) => ({ ...s, paymentMethod: v }))} options={METHODS} /><Field label="Reference No" value={loanForm.referenceNo} onChange={(v) => setLoanForm((s) => ({ ...s, referenceNo: v }))} /><Field label="Attachment URL" value={loanForm.attachmentUrl} onChange={(v) => setLoanForm((s) => ({ ...s, attachmentUrl: v }))} /><div className="md:col-span-3"><Field label="Notes/Reason" value={loanForm.notes} onChange={(v) => setLoanForm((s) => ({ ...s, notes: v }))} /></div><button className="md:col-span-3 rounded-xl bg-emerald-600 text-white py-2.5 font-semibold">Save Loan</button></form></Section>

    <Section title={tab === "received" ? "Return Received Loan" : "Return Given Loan"}><form onSubmit={createReturn} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Select required label={`Select ${tab === "received" ? "Received" : "Given"} Loan`} value={returnForm.loanId} onChange={(v) => setReturnForm((s) => ({ ...s, loanId: v }))} options={openLoans.map((l) => [l._id, `${l.partyName} | Principal: ${l.principalAmount} | Remaining: ${l.remainingAmount}`])} /><Field required type="number" label={tab === "received" ? "Return Amount" : "Received Amount"} value={returnForm.amount} onChange={(v) => setReturnForm((s) => ({ ...s, amount: v }))} /><Field required type="date" label={tab === "received" ? "Return Date" : "Received Date"} value={returnForm.paymentDate} onChange={(v) => setReturnForm((s) => ({ ...s, paymentDate: v }))} /><Select required label="Account" value={returnForm.accountId} onChange={(v) => setReturnForm((s) => ({ ...s, accountId: v }))} options={accounts.map((a) => [a._id, `${a.accountName} (${a.currency})`])} /><Select label="Payment Method" value={returnForm.method} onChange={(v) => setReturnForm((s) => ({ ...s, method: v }))} options={METHODS} /><Field label="Reference No" value={returnForm.referenceNo} onChange={(v) => setReturnForm((s) => ({ ...s, referenceNo: v }))} /><Field label="Attachment URL" value={returnForm.attachmentUrl} onChange={(v) => setReturnForm((s) => ({ ...s, attachmentUrl: v }))} /><div className="md:col-span-3"><Field label="Notes" value={returnForm.notes} onChange={(v) => setReturnForm((s) => ({ ...s, notes: v }))} /></div><button className="md:col-span-3 rounded-xl bg-zinc-900 text-white py-2.5 font-semibold">Save Return Entry</button></form></Section>

    <Section title={`${tab === "received" ? "Received" : "Given"} Loans Ledger`}><div className="overflow-auto rounded-xl border"><table className="w-full min-w-[980px] text-sm"><thead className="bg-zinc-50"><tr><th className="px-3 py-2 text-left">Loan ID</th><th className="px-3 py-2 text-left">Party</th><th className="px-3 py-2 text-left">Principal</th><th className="px-3 py-2 text-left">Total Returned/Received</th><th className="px-3 py-2 text-left">Remaining</th><th className="px-3 py-2 text-left">Loan Date</th><th className="px-3 py-2 text-left">Due Date</th><th className="px-3 py-2 text-left">Status</th><th className="px-3 py-2 text-left">Actions</th></tr></thead><tbody>{loans.length === 0 ? <tr><td className="px-3 py-6" colSpan={9}>No loans found.</td></tr> : loans.map((loan) => <tr key={loan._id} className="border-t"><td className="px-3 py-2">{loan._id.slice(-8).toUpperCase()}</td><td className="px-3 py-2">{loan.partyName}</td><td className="px-3 py-2">{Number(loan.principalAmount).toLocaleString()}</td><td className="px-3 py-2">{Number(loan.totalReturnedOrReceived).toLocaleString()}</td><td className="px-3 py-2 font-semibold">{Number(loan.remainingAmount).toLocaleString()}</td><td className="px-3 py-2">{new Date(loan.loanDate).toLocaleDateString()}</td><td className="px-3 py-2">{loan.dueDate ? new Date(loan.dueDate).toLocaleDateString() : "-"}</td><td className="px-3 py-2 capitalize">{loan.status}</td><td className="px-3 py-2"><div className="flex gap-2"><button onClick={() => setSelectedLoan(loan._id)} className="rounded border px-2 py-1">View Details</button><button onClick={() => setReturnForm((s) => ({ ...s, loanId: loan._id }))} className="rounded border px-2 py-1">Add Return</button></div></td></tr>)}</tbody></table></div></Section>

    {loanDetail?.loan ? <Section title={`Loan Detail — ${loanDetail.loan.partyName}`}><div className="grid md:grid-cols-3 gap-4"><Card title="Principal" value={Number(loanDetail.loan.principalAmount || 0).toLocaleString()} /><Card title="Total Returned/Received" value={Number(loanDetail.loan.totalReturnedOrReceived || 0).toLocaleString()} /><Card title="Remaining" value={Number(loanDetail.loan.remainingAmount || 0).toLocaleString()} /></div><div className="mt-4 overflow-auto rounded-xl border"><table className="w-full min-w-[900px] text-sm"><thead className="bg-zinc-50"><tr><th className="px-3 py-2 text-left">Date</th><th className="px-3 py-2 text-left">Amount</th><th className="px-3 py-2 text-left">Account</th><th className="px-3 py-2 text-left">Method</th><th className="px-3 py-2 text-left">Reference</th><th className="px-3 py-2 text-left">Notes</th><th className="px-3 py-2 text-left">Attachment</th></tr></thead><tbody>{loanDetail.payments.length === 0 ? <tr><td colSpan={7} className="px-3 py-6">No return history yet.</td></tr> : loanDetail.payments.map((p) => <tr key={p._id} className="border-t"><td className="px-3 py-2">{new Date(p.paymentDate).toLocaleString()}</td><td className="px-3 py-2">{Number(p.amount).toLocaleString()}</td><td className="px-3 py-2">{p.accountId?.accountName || "-"}</td><td className="px-3 py-2">{p.method}</td><td className="px-3 py-2">{p.referenceNo || "-"}</td><td className="px-3 py-2">{p.notes || "-"}</td><td className="px-3 py-2">{p.attachmentUrl ? <a href={p.attachmentUrl} className="underline" target="_blank">Open</a> : "-"}</td></tr>)}</tbody></table></div></Section> : null}
  </div></AdminShell>;
}

function Section({ title, children }) { return <div className="rounded-2xl bg-white border shadow-sm p-5"><div className="text-lg font-semibold mb-3">{title}</div>{children}</div>; }
function Card({ title, value }) { return <div className="rounded-xl border p-3"><div className="text-zinc-500 text-xs">{title}</div><div className="font-semibold text-lg mt-1">{value}</div></div>; }
function Field({ label, value, onChange, type = "text", required = false }) { return <label className="text-sm"><div className="mb-1">{label}</div><input required={required} type={type} value={value} onChange={(e) => onChange(e.target.value)} className="w-full rounded-xl border px-3 py-2"/></label>; }
function Select({ label, value, onChange, options, required = false }) { return <label className="text-sm"><div className="mb-1">{label}</div><select required={required} value={value} onChange={(e) => onChange(e.target.value)} className="w-full rounded-xl border px-3 py-2"><option value="">Select...</option>{options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>; }
