"use client";
import { useEffect, useState } from "react";
import apiClient from "../../../services/apiClient";
const tabs = [["tickets","Tickets"],["orders","Service Orders"],["assets","Customer Assets"],["contracts","AMC Contracts"]];
const money = (v) => `PKR ${Number(v||0).toLocaleString()}`;
const idOf = (r={}) => r._id || r.id || r.ticketNo || r.orderNo || r.assetNo || r.contractNo;
function statusBadge(s){ const ok=["active","completed","closed","resolved"].includes(String(s)); return <span className={`rounded-full px-3 py-1 text-xs font-black ${ok?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-700"}`}>{s||"draft"}</span>; }
function printPayload(title,payload){ const w=window.open("","_blank"); if(!w)return; w.document.write(`<html><head><title>${title}</title><style>body{font-family:Arial;padding:24px;color:#111827}.brand{font-size:20px;font-weight:800}pre{white-space:pre-wrap;border:1px solid #e5e7eb;border-radius:16px;padding:16px;background:#f8fafc}</style></head><body><div class="brand">Rawyan ERP</div><h1>${title}</h1><pre>${JSON.stringify(payload,null,2)}</pre><script>window.print()</script></body></html>`); w.document.close(); }
function exportCsv(name,rows=[]){ const cols=Object.keys(rows[0]||{empty:""}); const csv=[cols.join(","),...rows.map(r=>cols.map(c=>`"${String(r[c]??"").replaceAll('"','""')}"`).join(","))].join("\n"); const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); const a=document.createElement("a"); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); }
const ticketEmpty={customerName:"",subject:"",priority:"medium",slaHours:24,assignedToName:""};
const orderEmpty={ticketId:"",customerName:"",technicianName:"",serviceType:"repair",laborAmount:0,warehouseName:"Main Warehouse",lines:[]};
const assetEmpty={customerName:"",assetName:"",serialNo:"",modelNo:"",location:""};
const contractEmpty={customerName:"",assetName:"",contractValue:0,visitFrequency:"monthly",billingCycle:"monthly"};
export default function ServicePortalPage(){
 const [tab,setTab]=useState("tickets"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[overview,setOverview]=useState({}),[tickets,setTickets]=useState([]),[orders,setOrders]=useState([]),[assets,setAssets]=useState([]),[contracts,setContracts]=useState([]),[technicians,setTechnicians]=useState([]);
 const [ticketForm,setTicketForm]=useState(ticketEmpty),[orderForm,setOrderForm]=useState(orderEmpty),[assetForm,setAssetForm]=useState(assetEmpty),[contractForm,setContractForm]=useState(contractEmpty);
 async function load(){ setLoading(true); setError(""); try{ const [ov,t,o,a,c,tech]=await Promise.all([apiClient("/service/overview"),apiClient("/service/tickets"),apiClient("/service/orders"),apiClient("/service/assets"),apiClient("/service/contracts"),apiClient("/service/technicians")]); setOverview(ov||{}); setTickets(t?.tickets||[]); setOrders(o?.orders||[]); setAssets(a?.assets||[]); setContracts(c?.contracts||[]); setTechnicians(tech?.technicians||[]); }catch(e){setError(e.message||"Unable to load Service ERP")}finally{setLoading(false)} }
 useEffect(()=>{load()},[]);
 async function submit(path, body, reset){ setSaving(true); setError(""); setNotice(""); try{ await apiClient(path,{method:"POST",body}); setNotice("Saved successfully."); reset&&reset(); await load(); }catch(e){setError(e.message||"Unable to save")}finally{setSaving(false)} }
 async function printDoc(type,row,title){ try{ printPayload(title, await apiClient(`/service/print/${type}/${idOf(row)}`)); }catch(e){setError(e.message||"Unable to print")} }
 async function updateTicket(row,status){ await submit(`/service/tickets/${idOf(row)}/status`,{status},{}) }
 async function completeOrder(row){ const proofUrl=window.prompt("Proof/document URL after Cloudflare R2 upload", row.proofUrl||""); if(proofUrl===null)return; await submit(`/service/orders/${idOf(row)}/complete`,{proofUrl,status:"completed"},{}) }
 const k=overview.kpis||{};
 return <div className="space-y-6"><div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.35em] text-emerald-600">Phase 8 Complete Module</p><div className="mt-2 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-3xl font-black text-slate-950">Service ERP</h2><p className="mt-2 max-w-4xl text-sm text-slate-600">Tickets, technician assignment, SLA, AMC contracts, customer assets, spare-parts stock posting, proof upload URL, and service print documents.</p></div><button onClick={load} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-black">Refresh</button></div></div>{error?<div className="rounded-3xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>:null}{notice?<div className="rounded-3xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{notice}</div>:null}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[{label:"Assets",value:k.assets||0},{label:"Active AMC",value:k.activeContracts||0},{label:"Open Tickets",value:k.openTickets||0},{label:"Service Revenue",value:money(k.serviceRevenue)}].map(x=><div key={x.label} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">{x.label}</p><p className="mt-3 text-2xl font-black text-slate-950">{x.value}</p></div>)}</div><div className="flex flex-wrap gap-2">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-full px-4 py-2 text-sm font-black ${tab===key?"bg-slate-950 text-white":"bg-white text-slate-600 border border-slate-200"}`}>{label}</button>)}</div>{loading?<div className="rounded-3xl bg-white p-6 text-sm text-slate-500">Loading Service ERP…</div>:null}
 {tab==="tickets"?<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Form title="Create Ticket"><input value={ticketForm.customerName} onChange={e=>setTicketForm({...ticketForm,customerName:e.target.value})} placeholder="Customer name"/><input value={ticketForm.subject} onChange={e=>setTicketForm({...ticketForm,subject:e.target.value})} placeholder="Issue / subject"/><select value={ticketForm.priority} onChange={e=>setTicketForm({...ticketForm,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>urgent</option></select><select value={ticketForm.assignedToName} onChange={e=>setTicketForm({...ticketForm,assignedToName:e.target.value})}><option value="">Assign later</option>{technicians.map(t=><option key={idOf(t)}>{t.fullName||t.username}</option>)}</select><button disabled={saving} onClick={()=>submit("/service/tickets",ticketForm,()=>setTicketForm(ticketEmpty))}>Create Ticket</button></Form><DataTable title="Tickets" rows={tickets} columns={["No","Customer","Subject","Priority","Status","Actions"]} render={r=>[r.ticketNo,r.customerName,r.subject,r.priority,statusBadge(r.status),<div className="flex flex-wrap gap-2"><button onClick={()=>updateTicket(r,"in_progress")}>Start</button><button onClick={()=>updateTicket(r,"closed")}>Close</button><button onClick={()=>printDoc("ticket",r,"Service Ticket")}>Print</button></div>]}/></div>:null}
 {tab==="orders"?<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Form title="Create Service Order"><select value={orderForm.ticketId} onChange={e=>{const t=tickets.find(x=>idOf(x)===e.target.value);setOrderForm({...orderForm,ticketId:e.target.value,customerName:t?.customerName||orderForm.customerName})}}><option value="">Without ticket</option>{tickets.map(t=><option key={idOf(t)} value={idOf(t)}>{t.ticketNo} — {t.customerName}</option>)}</select><input value={orderForm.customerName} onChange={e=>setOrderForm({...orderForm,customerName:e.target.value})} placeholder="Customer name"/><input value={orderForm.technicianName} onChange={e=>setOrderForm({...orderForm,technicianName:e.target.value})} placeholder="Technician"/><input value={orderForm.laborAmount} onChange={e=>setOrderForm({...orderForm,laborAmount:e.target.value})} type="number" placeholder="Labor amount"/><button disabled={saving} onClick={()=>submit("/service/orders",orderForm,()=>setOrderForm(orderEmpty))}>Create Order</button></Form><DataTable title="Service Orders" rows={orders} columns={["No","Customer","Technician","Amount","Status","Actions"]} render={r=>[r.orderNo,r.customerName,r.technicianName,money(r.totals?.grandTotal),statusBadge(r.status),<div className="flex flex-wrap gap-2"><button onClick={()=>completeOrder(r)}>Complete</button><button onClick={()=>printDoc("order",r,"Service Order")}>Print</button></div>]}/></div>:null}
 {tab==="assets"?<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Form title="Register Customer Asset"><input value={assetForm.customerName} onChange={e=>setAssetForm({...assetForm,customerName:e.target.value})} placeholder="Customer name"/><input value={assetForm.assetName} onChange={e=>setAssetForm({...assetForm,assetName:e.target.value})} placeholder="Asset name"/><input value={assetForm.serialNo} onChange={e=>setAssetForm({...assetForm,serialNo:e.target.value})} placeholder="Serial no"/><input value={assetForm.location} onChange={e=>setAssetForm({...assetForm,location:e.target.value})} placeholder="Location"/><button disabled={saving} onClick={()=>submit("/service/assets",assetForm,()=>setAssetForm(assetEmpty))}>Save Asset</button></Form><DataTable title="Customer Assets" rows={assets} columns={["No","Customer","Asset","Serial","Status","Print"]} render={r=>[r.assetNo,r.customerName,r.assetName,r.serialNo,statusBadge(r.status),<button onClick={()=>printDoc("asset",r,"Customer Asset")}>Print</button>]}/></div>:null}
 {tab==="contracts"?<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Form title="Create AMC Contract"><input value={contractForm.customerName} onChange={e=>setContractForm({...contractForm,customerName:e.target.value})} placeholder="Customer name"/><input value={contractForm.assetName} onChange={e=>setContractForm({...contractForm,assetName:e.target.value})} placeholder="Asset name"/><input value={contractForm.contractValue} onChange={e=>setContractForm({...contractForm,contractValue:e.target.value})} type="number" placeholder="Contract value"/><input value={contractForm.visitFrequency} onChange={e=>setContractForm({...contractForm,visitFrequency:e.target.value})} placeholder="Visit frequency"/><button disabled={saving} onClick={()=>submit("/service/contracts",contractForm,()=>setContractForm(contractEmpty))}>Save Contract</button></Form><DataTable title="AMC Contracts" rows={contracts} columns={["No","Customer","Asset","Value","Status","Print"]} render={r=>[r.contractNo,r.customerName,r.assetName,money(r.contractValue),statusBadge(r.status),<button onClick={()=>printDoc("contract",r,"AMC Contract")}>Print</button>]}/></div>:null}</div> }
function Form({title,children}){return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-slate-950">{title}</h3><div className="mt-4 space-y-3 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-200 [&_input]:px-3 [&_input]:py-2 [&_input]:text-sm [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-slate-200 [&_select]:px-3 [&_select]:py-2 [&_select]:text-sm [&_button]:w-full [&_button]:rounded-2xl [&_button]:bg-gradient-to-r [&_button]:from-emerald-500 [&_button]:to-blue-600 [&_button]:px-4 [&_button]:py-3 [&_button]:text-sm [&_button]:font-black [&_button]:text-white">{children}</div></div>}
function DataTable({title,rows=[],columns=[],render}){return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div><h3 className="font-black text-slate-950">{title}</h3><p className="text-xs text-slate-500">{rows.length} records</p></div><button onClick={()=>exportCsv(`${title}.csv`,rows)} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">Export CSV</button></div><div className="overflow-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map(c=><th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={idOf(r)||i} className="border-t border-slate-100 align-top">{render(r).map((cell,j)=><td key={j} className="px-4 py-3 text-slate-700">{cell}</td>)}</tr>)}{!rows.length?<tr><td colSpan={columns.length} className="px-4 py-8 text-center text-slate-400">No records yet.</td></tr>:null}</tbody></table></div></div>}
