"use client";
import { useEffect, useState } from "react";
import AdminShell from "../components/AdminShell";
import { apiFetch } from "../../../lib/api";

export default function FieldListPage(){
  const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [edit,setEdit]=useState(null);
  const load=async()=>{setLoading(true); const d=await apiFetch('/fields'); setRows(d.fields||[]); setLoading(false);};
  useEffect(()=>{(async()=>{setLoading(true); const d=await apiFetch('/fields'); setRows(d.fields||[]); setLoading(false);})();},[]);
  async function save(){await apiFetch(`/fields/${edit._id}`,{method:'PUT',body:edit}); setEdit(null); load();}
  async function del(id){if(!confirm('Delete field?'))return; await apiFetch(`/fields/${id}`,{method:'DELETE'}); load();}
  return <AdminShell title="Field List" user={null}><div className="rounded-2xl bg-white border shadow-sm p-5"><div className="text-xl font-semibold">Fields</div><div className="mt-5 overflow-auto rounded-xl border"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-zinc-50"><tr><th className="px-3 py-2 border-b text-left">ID</th><th className="px-3 py-2 border-b text-left">Name</th><th className="px-3 py-2 border-b text-left">Warehouse</th><th className="px-3 py-2 border-b text-left">Region</th><th className="px-3 py-2 border-b text-left">Zone</th><th className="px-3 py-2 border-b text-left">Territory</th><th className="px-3 py-2 border-b text-left">Status</th><th className="px-3 py-2 border-b text-left">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="px-3 py-6 text-center">Loading...</td></tr>:rows.map(r=><tr key={r._id}><td className="px-3 py-2 border-b">{r.fieldId}</td><td className="px-3 py-2 border-b">{r.name}</td><td className="px-3 py-2 border-b">{r.warehouseName||'-'}</td><td className="px-3 py-2 border-b">{r.regionName||'-'}</td><td className="px-3 py-2 border-b">{r.zoneName||'-'}</td><td className="px-3 py-2 border-b">{r.territoryName||'-'}</td><td className="px-3 py-2 border-b">{r.status||'active'}</td><td className="px-3 py-2 border-b"><button className="rounded-lg border px-3 py-1 text-xs mr-2" onClick={()=>setEdit({...r})}>Edit</button><button className="rounded-lg border px-3 py-1 text-xs text-red-600" onClick={()=>del(r._id)}>Delete</button></td></tr>)}</tbody></table></div></div>{edit?<Modal edit={edit} setEdit={setEdit} onSave={save}/>:null}</AdminShell>
}
function Modal({edit,setEdit,onSave}){return <div className="fixed inset-0 z-50"><div className="absolute inset-0 bg-black/40" onClick={()=>setEdit(null)}/><div className="absolute right-0 top-0 h-full w-full sm:w-[520px] bg-white p-4"><div className="text-lg font-semibold">Edit Field</div><div className="mt-3 grid gap-3">{['fieldId','name','warehouseName','regionName','zoneName','territoryName'].map(f=><input key={f} value={edit[f]||''} onChange={e=>setEdit(s=>({...s,[f]:e.target.value}))} placeholder={f} className="rounded-xl border px-3 py-2"/>)}<select value={edit.status||'active'} onChange={e=>setEdit(s=>({...s,status:e.target.value}))} className="rounded-xl border px-3 py-2"><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div className="mt-4 flex gap-2"><button onClick={onSave} className="rounded-xl bg-emerald-600 text-white px-4 py-2 text-sm">Update</button><button onClick={()=>setEdit(null)} className="rounded-xl border px-4 py-2 text-sm">Cancel</button></div></div></div>}
