const express = require("express");
const { requireAuth } = require("../../../../utils/auth");
const { requireCompanyModule } = require("../../../../core/access/companyAccessGuard");
const controller = require("./retail-pos.controller");
const router = express.Router();
router.use(requireAuth, requireCompanyModule("retail-pos"));
router.get("/overview", controller.overview);
router.get("/sessions", controller.sessions);
router.post("/sessions/open", controller.openSession);
router.post("/sessions/:id/close", controller.closeSession);
router.get("/products", controller.products);
router.get("/customers", controller.customers);
router.get("/sales", controller.sales);
router.post("/sales", controller.createSale);
router.post("/sales/:id/return", controller.returnSale);
router.get("/print/:type/:id", controller.printDocument);
module.exports = router;
