const express = require("express");
const { requireAuth } = require("../../utils/auth");
const controller = require("./manufacturing.controller");
const router = express.Router();
router.use(requireAuth);
router.get("/overview", controller.overview);
router.get("/products", controller.products);
router.get("/warehouses", controller.warehouses);
router.get("/boms", controller.boms);
router.post("/boms", controller.createBom);
router.get("/production-orders", controller.productionOrders);
router.post("/production-orders", controller.createProductionOrder);
router.post("/production-orders/:id/issue-materials", controller.issueMaterials);
router.post("/production-orders/:id/receive-finished-goods", controller.receiveFinishedGoods);
router.post("/production-orders/:id/quality-check", controller.createQualityCheck);
router.get("/quality-checks", controller.qualityChecks);
router.post("/quality-checks", controller.createQualityCheck);
router.get("/maintenance", controller.maintenance);
router.post("/maintenance", controller.createMaintenance);
router.get("/print/:type/:id", controller.printDocument);
module.exports = router;
