"use client";
import { useEffect, useState } from "react";
import financeService from "../../../services/financeService";

const TABS = [["overview", "Overview"], ["primary", "Company Receivables"], ["customer", "Distributor Customer Receivables"], ["supplier", "Supplier Payables"], ["accounts", "Cash / Bank Accounts"], ["ledger", "Ledger"], ["expenses", "Expenses"], ["loans", "Loans"]];
function money(value) { return `PKR ${Number(value || 0).toLocaleString()}`; }
function status(status) { const s = String(status || "open"); const cls = s === "paid" || s === "posted" || s === "active" ? "bg-emerald-50 text-emerald-700" : s === "partial" ? "bg-blue-50 text-blue-700" : s === "pending" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-700"; return <span className={`rounded-full px-3 py-1 text-xs font-black ${cls}`}>{s}</span>; }
const emptyAccount = { accountName: "", accountType: "cash", openingBalance: 0, accountNumber: "", notes: "" };

export default function FinanceFoundationPage({ mode = "finance" }) {
  const [tab, setTab] = useState(mode === "receipts" ? "primary" : mode === "payments" ? "supplier" : "overview");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [accountForm, setAccountForm] = useState(emptyAccount);
  const [data, setData] = useState({ kpis: {}, distributorInvoices: [], distributorReceipts: [], customerInvoices: [], customerReceipts: [], supplierInvoices: [], supplierPayments: [], accounts: [], transactions: [], expenses: [], loans: [] });

  async function load() { setLoading(true); setError(""); try { setData(await financeService.overview()); } catch (e) { setError(e.message || "Unable to load finance data"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function action(label, fn) { setSaving(true); setError(""); setNotice(""); try { const res = await fn(); setNotice(res?.message || `${label} completed successfully.`); await load(); } catch (e) { setError(e.message || `${label} failed`); } finally { setSaving(false); } }
  async function createAccount() { await action("Account creation", () => financeService.createAccount(accountForm)); setAccountForm(emptyAccount); }

  return <div className="space-y-6">
    <div className="rounded-[2rem] bg-gradient-to-r from-slate-950 via-emerald-700 to-cyan-500 p-6 text-white shadow-lg"><p className="text-xs font-black uppercase tracking-[0.35em] text-cyan-100">Phase 13 Finance</p><h2 className="mt-2 text-3xl font-black">Finance, Accounts, Expenses, Loans & Ledgers</h2><p className="mt-2 max-w-4xl text-sm text-cyan-50">Company finance handles supplier payables, distributor receivables, accounts, expenses, loans, and ledgers. Distributor finance handles customer receivables, customer receipts, and distributor expense flow.</p></div>
    <div className="flex flex-wrap gap-2">{TABS.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`rounded-full px-4 py-2 text-sm font-bold ${tab === key ? "bg-slate-950 text-white" : "bg-white text-slate-600 shadow-sm ring-1 ring-slate-200"}`}>{label}</button>)}</div>
    {error ? <div className="rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-600">{error}</div> : null}{notice ? <div className="rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</div> : null}
    {loading ? <div className="rounded-3xl border border-slate-200 bg-white p-6 text-slate-500 shadow-sm">Loading finance data…</div> : null}
    {!loading && tab === "overview" ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Primary Receivable", data.kpis?.primaryReceivable, "Distributor invoice balance"], ["Customer Receivable", data.kpis?.customerReceivable, "Customer invoice balance"], ["Supplier Payable", data.kpis?.supplierPayable, "Supplier invoice balance"], ["Cash/Bank Balance", data.kpis?.accountBalance, "Tracked account balance"], ["Cash In", data.kpis?.cashIn, "Ledger cash in"], ["Cash Out", data.kpis?.cashOut, "Ledger cash out"], ["Open Expenses", data.kpis?.pendingExpenses, "Pending/approved expenses"], ["Loan Receivable", data.kpis?.loansReceivable, "Given loans still open"], ["Loan Payable", data.kpis?.loansPayable, "Received loans still open"]].map(([label, value, help]) => <div key={label} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">{label}</p><p className="mt-3 text-2xl font-black text-slate-950">{money(value)}</p><p className="mt-2 text-sm text-slate-500">{help}</p></div>)}</div> : null}
    {!loading && tab === "primary" ? <div className="grid gap-5 xl:grid-cols-2"><Table title="Distributor Invoices" rows={data.distributorInvoices} columns={["Invoice", "Distributor", "Total", "Balance", "Status", "Action"]} render={(row) => [row.documentNo, row.distributor?.partyName || "-", money(row.invoiceTotal), money(row.balanceAmount), status(row.paymentStatus), Number(row.balanceAmount || 0) > 0 ? <button key="r" disabled={saving} onClick={() => action("Distributor receipt", () => financeService.receiveDistributorInvoice(row._id, { amount: row.balanceAmount, paymentMethod: "cash" }))} className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Receive Payment</button> : <span key="paid" className="text-xs font-bold text-slate-500">Paid</span>]} /><Table title="Distributor Receipts" rows={data.distributorReceipts} columns={["Receipt", "Distributor", "Amount", "Method", "Status"]} render={(row) => [row.documentNo, row.payer?.partyName || row.distributorId || "-", money(row.amount), row.paymentMethod || "-", status(row.status)]} /></div> : null}
    {!loading && tab === "customer" ? <div className="grid gap-5 xl:grid-cols-2"><Table title="Customer Invoices" rows={data.customerInvoices} columns={["Invoice", "Customer", "Total", "Balance", "Status", "Action"]} render={(row) => [row.documentNo, row.customer?.partyName || "-", money(row.invoiceTotal), money(row.balanceAmount), status(row.paymentStatus), Number(row.balanceAmount || 0) > 0 ? <button key="cr" disabled={saving} onClick={() => action("Customer receipt", () => financeService.receiveCustomerInvoice(row._id, { amount: row.balanceAmount, paymentMethod: "cash" }))} className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Receive Customer</button> : <span key="paid" className="text-xs font-bold text-slate-500">Paid</span>]} /><Table title="Customer Receipts" rows={data.customerReceipts} columns={["Receipt", "Customer", "Amount", "Method", "Status"]} render={(row) => [row.documentNo, row.customer?.partyName || "-", money(row.amount), row.paymentMethod || "-", status(row.status)]} /></div> : null}
    {!loading && tab === "supplier" ? <div className="grid gap-5 xl:grid-cols-2"><Table title="Supplier Invoices" rows={data.supplierInvoices} columns={["Invoice", "Supplier", "Total", "Balance", "Status", "Action"]} render={(row) => [row.documentNo, row.supplier?.partyName || "-", money(row.invoiceTotal), money(row.balanceAmount), status(row.paymentStatus), Number(row.balanceAmount || 0) > 0 ? <button key="p" disabled={saving} onClick={() => action("Supplier payment", () => financeService.paySupplierInvoice(row._id, { amount: row.balanceAmount, paymentMethod: "cash" }))} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">Pay</button> : <span key="paid" className="text-xs font-bold text-slate-500">Paid</span>]} /><Table title="Supplier Payments" rows={data.supplierPayments} columns={["Payment", "Supplier", "Amount", "Method", "Status"]} render={(row) => [row.documentNo, row.supplier?.partyName || "-", money(row.amount), row.paymentMethod || "-", status(row.status)]} /></div> : null}
    {!loading && tab === "accounts" ? <div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black text-slate-950">Create Cash / Bank Account</h3><div className="mt-4 grid gap-3"><input value={accountForm.accountName} onChange={(e) => setAccountForm((p) => ({ ...p, accountName: e.target.value }))} placeholder="Account name" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm" /><select value={accountForm.accountType} onChange={(e) => setAccountForm((p) => ({ ...p, accountType: e.target.value }))} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm"><option value="cash">Cash</option><option value="bank">Bank</option><option value="easypaisa">Easypaisa</option><option value="jazzcash">JazzCash</option><option value="other">Other</option></select><input value={accountForm.accountNumber} onChange={(e) => setAccountForm((p) => ({ ...p, accountNumber: e.target.value }))} placeholder="Account number" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm" /><input value={accountForm.openingBalance} onChange={(e) => setAccountForm((p) => ({ ...p, openingBalance: e.target.value }))} placeholder="Opening balance" type="number" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm" /><button onClick={createAccount} disabled={saving} className="rounded-2xl bg-slate-950 px-4 py-3 text-sm font-black text-white">Create Account</button></div></div><Table title="Cash / Bank Accounts" rows={data.accounts} columns={["Account", "Type", "Balance", "Status"]} render={(row) => [row.accountName || row.accountId, row.accountType || "-", money(row.currentBalance || row.openingBalance), status(row.status || "active")]} /></div> : null}
    {!loading && tab === "ledger" ? <Table title="Account Ledger" rows={data.transactions} columns={["Date", "Account", "Type", "Amount", "Reference", "Description"]} render={(row) => [row.transactionDate ? new Date(row.transactionDate).toLocaleDateString() : "-", row.accountId?.accountName || row.accountId || "-", row.type, money(row.amount), row.referenceType || "-", row.description || "-"]} /> : null}
    {!loading && tab === "expenses" ? <Table title="Expenses" rows={data.expenses} columns={["Date", "Title", "Section", "Category", "Amount", "Status"]} render={(row) => [row.expenseDate ? new Date(row.expenseDate).toLocaleDateString() : "-", row.title || row.description || "-", row.section || "-", row.category || row.expenseType || "-", money(row.amount), status(row.status)]} /> : null}
    {!loading && tab === "loans" ? <Table title="Loans" rows={data.loans} columns={["Party", "Type", "Principal", "Remaining", "Due Date", "Status"]} render={(row) => [row.partyName || "-", row.loanType || "-", money(row.principalAmount), money(row.remainingAmount), row.dueDate ? new Date(row.dueDate).toLocaleDateString() : "-", status(row.status)]} /> : null}
  </div>;
}
function Table({ title, rows = [], columns = [], render }) { return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-4"><h3 className="font-black text-slate-950">{title}</h3><p className="text-xs text-slate-500">{rows.length} records</p></div><div className="overflow-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map((c) => <th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody>{rows.map((row, idx) => <tr key={row._id || idx} className="border-t border-slate-100">{render(row).map((cell, i) => <td key={i} className="px-4 py-3 align-middle text-slate-700">{cell}</td>)}</tr>)}{!rows.length ? <tr><td colSpan={columns.length} className="px-4 py-8 text-center text-slate-400">No records yet.</td></tr> : null}</tbody></table></div></div>; }
