"use client";
import { useEffect, useState } from "react";
import apiClient from "../../../services/apiClient";
const tabs=[["shipments","Shipments"],["lc","Letters of Credit"],["landed","Landed Cost"]];
const money=(v)=>`PKR ${Number(v||0).toLocaleString()}`; const idOf=(r={})=>r._id||r.id||r.shipmentNo||r.lcNo||r.costNo;
function statusBadge(s){const ok=["received","closed","settled","posted"].includes(String(s));return <span className={`rounded-full px-3 py-1 text-xs font-black ${ok?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-700"}`}>{s||"draft"}</span>}
function printPayload(title,payload){const w=window.open("","_blank");if(!w)return;w.document.write(`<html><head><title>${title}</title><style>body{font-family:Arial;padding:24px;color:#111827}.brand{font-size:20px;font-weight:800}pre{white-space:pre-wrap;border:1px solid #e5e7eb;border-radius:16px;padding:16px;background:#f8fafc}</style></head><body><div class="brand">Rawyan ERP</div><h1>${title}</h1><pre>${JSON.stringify(payload,null,2)}</pre><script>window.print()</script></body></html>`);w.document.close()}
function exportCsv(name,rows=[]){const cols=Object.keys(rows[0]||{empty:""});const csv=[cols.join(","),...rows.map(r=>cols.map(c=>`"${String(r[c]??"").replaceAll('"','""')}"`).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
const shipmentEmpty={shipmentType:"import",supplierName:"",customerName:"",containerNo:"",blNo:"",currency:"USD",exchangeRate:1,warehouseName:"Main Warehouse",lines:[{productName:"",qty:1,unitCost:0,unitPrice:0}]};
const lcEmpty={bankName:"",supplierName:"",currency:"USD",amount:0,exchangeRate:1};
const landedEmpty={shipmentId:"",freight:0,customsDuty:0,clearing:0,insurance:0,otherCharges:0};
export default function TradingPortalPage(){
 const [tab,setTab]=useState("shipments"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[overview,setOverview]=useState({}),[shipments,setShipments]=useState([]),[lcs,setLcs]=useState([]),[landed,setLanded]=useState([]),[warehouses,setWarehouses]=useState([]),[products,setProducts]=useState([]);
 const [shipmentForm,setShipmentForm]=useState(shipmentEmpty),[lcForm,setLcForm]=useState(lcEmpty),[landedForm,setLandedForm]=useState(landedEmpty);
 async function load(){setLoading(true);setError("");try{const[ov,sh,lc,lcst,wh,pr]=await Promise.all([apiClient("/trading/overview"),apiClient("/trading/shipments"),apiClient("/trading/letters-of-credit"),apiClient("/trading/landed-costs"),apiClient("/trading/warehouses"),apiClient("/trading/products")]);setOverview(ov||{});setShipments(sh?.shipments||[]);setLcs(lc?.lettersOfCredit||[]);setLanded(lcst?.landedCosts||[]);setWarehouses(wh?.warehouses||[]);setProducts(pr?.products||[])}catch(e){setError(e.message||"Unable to load Trading ERP")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function submit(path,body,reset){setSaving(true);setError("");setNotice("");try{await apiClient(path,{method:"POST",body});setNotice("Saved successfully.");reset&&reset();await load()}catch(e){setError(e.message||"Unable to save")}finally{setSaving(false)}}
 function setLine(i,key,value){const lines=shipmentForm.lines.map((l,x)=>x===i?{...l,[key]:value}:l); if(key==="productId"){const p=products.find(p=>String(p.productId||p._id||p.code)===String(value)); lines[i]={...lines[i],productName:p?.name||p?.productName||lines[i].productName,unitCost:p?.costPrice||p?.tradePrice||0,unitPrice:p?.retailPrice||p?.customerPrice||0};} setShipmentForm({...shipmentForm,lines})}
 async function statusShipment(row,status){await submit(`/trading/shipments/${idOf(row)}/status`,{status},{})}
 async function printDoc(type,row,title){try{printPayload(title,await apiClient(`/trading/print/${type}/${idOf(row)}`))}catch(e){setError(e.message||"Unable to print")}}
 const k=overview.kpis||{};
 return <div className="space-y-6"><div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.35em] text-emerald-600">Phase 8 Complete Module</p><div className="mt-2 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-3xl font-black text-slate-950">Trading / Import ERP</h2><p className="mt-2 max-w-4xl text-sm text-slate-600">Import/export shipments, LC management, container tracking, landed cost allocation, warehouse receipt posting, document upload URL, print and CSV export.</p></div><button onClick={load} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-black">Refresh</button></div></div>{error?<div className="rounded-3xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>:null}{notice?<div className="rounded-3xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{notice}</div>:null}<div className="grid gap-4 md:grid-cols-3">{[{label:"Open Shipments",value:k.openShipments||0},{label:"Active LCs",value:k.activeLc||0},{label:"Posted Landed Cost",value:money(k.landedCost)}].map(x=><div key={x.label} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">{x.label}</p><p className="mt-3 text-2xl font-black text-slate-950">{x.value}</p></div>)}</div><div className="flex flex-wrap gap-2">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-full px-4 py-2 text-sm font-black ${tab===key?"bg-slate-950 text-white":"bg-white text-slate-600 border border-slate-200"}`}>{label}</button>)}</div>{loading?<div className="rounded-3xl bg-white p-6 text-sm text-slate-500">Loading Trading ERP…</div>:null}
 {tab==="shipments"?<div className="grid gap-6 xl:grid-cols-[420px_1fr]"><Form title="Create Shipment"><select value={shipmentForm.shipmentType} onChange={e=>setShipmentForm({...shipmentForm,shipmentType:e.target.value})}><option>import</option><option>export</option><option>local</option></select><input value={shipmentForm.supplierName} onChange={e=>setShipmentForm({...shipmentForm,supplierName:e.target.value})} placeholder="Supplier name"/><input value={shipmentForm.customerName} onChange={e=>setShipmentForm({...shipmentForm,customerName:e.target.value})} placeholder="Customer name"/><input value={shipmentForm.containerNo} onChange={e=>setShipmentForm({...shipmentForm,containerNo:e.target.value})} placeholder="Container no"/><input value={shipmentForm.blNo} onChange={e=>setShipmentForm({...shipmentForm,blNo:e.target.value})} placeholder="BL / AWB no"/><select value={shipmentForm.warehouseId} onChange={e=>{const w=warehouses.find(w=>String(w.warehouseId||w._id)===e.target.value);setShipmentForm({...shipmentForm,warehouseId:e.target.value,warehouseName:w?.name||w?.warehouseName||""})}}><option value="">Select warehouse</option>{warehouses.map(w=><option key={idOf(w)} value={w.warehouseId||w._id}>{w.name||w.warehouseName}</option>)}</select>{shipmentForm.lines.map((l,i)=><div key={i} className="grid gap-2 rounded-2xl border border-slate-200 p-3 md:grid-cols-[1fr_70px_90px_auto]"><select value={l.productId||""} onChange={e=>setLine(i,"productId",e.target.value)}><option value="">Manual item</option>{products.map(p=><option key={idOf(p)} value={p.productId||p._id||p.code}>{p.name||p.productName||p.code}</option>)}</select><input value={l.qty} onChange={e=>setLine(i,"qty",e.target.value)} type="number"/><input value={l.unitCost} onChange={e=>setLine(i,"unitCost",e.target.value)} type="number"/><button onClick={()=>setShipmentForm({...shipmentForm,lines:shipmentForm.lines.filter((_,x)=>x!==i)})}>Remove</button></div>)}<button onClick={()=>setShipmentForm({...shipmentForm,lines:[...shipmentForm.lines,{productName:"",qty:1,unitCost:0,unitPrice:0}]})}>Add Line</button><button disabled={saving} onClick={()=>submit("/trading/shipments",shipmentForm,()=>setShipmentForm(shipmentEmpty))}>Create Shipment</button></Form><DataTable title="Shipments" rows={shipments} columns={["No","Type","Party","Container","Total","Landed/Unit","Status","Actions"]} render={r=>[r.shipmentNo,r.shipmentType,r.supplierName||r.customerName,r.containerNo,money(r.totals?.grandTotal),money(r.landedCostPerUnit),statusBadge(r.status),<div className="flex flex-wrap gap-2"><button onClick={()=>statusShipment(r,"in_transit")}>Transit</button><button onClick={()=>statusShipment(r,"received")}>Receive</button><button onClick={()=>printDoc("shipment",r,"Trading Shipment")}>Print</button></div>]}/></div>:null}
 {tab==="lc"?<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Form title="Create Letter of Credit"><input value={lcForm.bankName} onChange={e=>setLcForm({...lcForm,bankName:e.target.value})} placeholder="Bank name"/><input value={lcForm.supplierName} onChange={e=>setLcForm({...lcForm,supplierName:e.target.value})} placeholder="Supplier"/><input value={lcForm.currency} onChange={e=>setLcForm({...lcForm,currency:e.target.value})} placeholder="Currency"/><input value={lcForm.amount} onChange={e=>setLcForm({...lcForm,amount:e.target.value})} type="number" placeholder="Amount"/><button disabled={saving} onClick={()=>submit("/trading/letters-of-credit",lcForm,()=>setLcForm(lcEmpty))}>Save LC</button></Form><DataTable title="Letters of Credit" rows={lcs} columns={["LC No","Bank","Supplier","Amount","Status","Print"]} render={r=>[r.lcNo,r.bankName,r.supplierName,`${r.currency} ${Number(r.amount||0).toLocaleString()}`,statusBadge(r.status),<button onClick={()=>printDoc("lc",r,"Letter of Credit")}>Print</button>]}/></div>:null}
 {tab==="landed"?<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Form title="Post Landed Cost"><select value={landedForm.shipmentId} onChange={e=>setLandedForm({...landedForm,shipmentId:e.target.value})}><option value="">Select shipment</option>{shipments.map(s=><option key={idOf(s)} value={idOf(s)}>{s.shipmentNo}</option>)}</select><input value={landedForm.freight} onChange={e=>setLandedForm({...landedForm,freight:e.target.value})} type="number" placeholder="Freight"/><input value={landedForm.customsDuty} onChange={e=>setLandedForm({...landedForm,customsDuty:e.target.value})} type="number" placeholder="Customs duty"/><input value={landedForm.clearing} onChange={e=>setLandedForm({...landedForm,clearing:e.target.value})} type="number" placeholder="Clearing"/><input value={landedForm.insurance} onChange={e=>setLandedForm({...landedForm,insurance:e.target.value})} type="number" placeholder="Insurance"/><input value={landedForm.otherCharges} onChange={e=>setLandedForm({...landedForm,otherCharges:e.target.value})} type="number" placeholder="Other charges"/><button disabled={saving} onClick={()=>submit("/trading/landed-costs",landedForm,()=>setLandedForm(landedEmpty))}>Post Landed Cost</button></Form><DataTable title="Landed Costs" rows={landed} columns={["No","Shipment","Freight","Duty","Total","Status","Print"]} render={r=>[r.costNo,r.shipmentNo,money(r.freight),money(r.customsDuty),money(r.totalCost),statusBadge(r.status),<button onClick={()=>printDoc("landed-cost",r,"Landed Cost")}>Print</button>]}/></div>:null}</div>}
function Form({title,children}){return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-slate-950">{title}</h3><div className="mt-4 space-y-3 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-200 [&_input]:px-3 [&_input]:py-2 [&_input]:text-sm [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-slate-200 [&_select]:px-3 [&_select]:py-2 [&_select]:text-sm [&_button]:rounded-xl [&_button]:bg-slate-950 [&_button]:px-3 [&_button]:py-2 [&_button]:text-xs [&_button]:font-black [&_button]:text-white">{children}</div></div>}
function DataTable({title,rows=[],columns=[],render}){return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div><h3 className="font-black text-slate-950">{title}</h3><p className="text-xs text-slate-500">{rows.length} records</p></div><button onClick={()=>exportCsv(`${title}.csv`,rows)} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">Export CSV</button></div><div className="overflow-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map(c=><th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={idOf(r)||i} className="border-t border-slate-100 align-top">{render(r).map((cell,j)=><td key={j} className="px-4 py-3 text-slate-700">{cell}</td>)}</tr>)}{!rows.length?<tr><td colSpan={columns.length} className="px-4 py-8 text-center text-slate-400">No records yet.</td></tr>:null}</tbody></table></div></div>}
